#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ERA5 validation against INMET 1991–2020 climatological normals.

Purpose
-------
Compare ERA5 monthly climatologies with INMET 1991–2020 climatological normals
at station locations. This evaluation focuses on the baseline climatology used
for heatwave-threshold analyses; it does not evaluate individual heatwave
events or daily weather variability.

INMET variables
---------------
The directory supplied through ``--normal-dir`` must contain:

  Normal-Climatologica-ESTAÇÕES.xlsx
  Normal-Climatologica-TMAX.xlsx
  Normal-Climatologica-TMIN.xlsx
  Normal-Climatologica-TORV.xlsx
  Normal-Climatologica-UR.xlsx
  Normal-Climatologica-VENTIN.xlsx
  Normal-Climatologica-TMEDUMID.xlsx

ERA5 processing
---------------
Two input modes are supported:

``daily``
    Uses daily ERA5 files previously generated by the Figure 01 workflow.
    This is the recommended mode for climatological-normal evaluation.

``hourly``
    Uses hourly ERA5 single-level files and permits daily aggregation in UTC
    or by fixed state-level UTC offsets.

``auto``
    Uses daily files when supplied and available; otherwise uses hourly files.

At each INMET station, the nearest ERA5 grid cell is used. TMAX and TMIN are
derived from daily extrema. Dew-point temperature, relative humidity, 10-m wind
speed, and wet-bulb temperature are evaluated as monthly climatological means.

Outputs
-------
Station-month paired values, station-level metrics, regional/national Taylor
metrics, station metadata, nearest-grid metadata, an Excel workbook, software
metadata, and a publication-ready validation figure.

Example: daily mode
-------------------
python era5_inmet_climatological_normals_validation.py \
    --normal-dir /path/to/inmet_normals_1991_2020 \
    --era5-daily-dir /path/to/figure_01_outputs/cache/era5_daily \
    --source daily \
    --states-shapefile /path/to/brazil_states.shp \
    --output-dir ./outputs/era5_inmet_climatology \
    --reuse-era5-cache

Example: hourly mode
--------------------
python era5_inmet_climatological_normals_validation.py \
    --normal-dir /path/to/inmet_normals_1991_2020 \
    --era5-hourly-glob "/path/to/era5_hourly_*.nc" \
    --source hourly \
    --states-shapefile /path/to/brazil_states.shp \
    --output-dir ./outputs/era5_inmet_climatology \
    --daily-time-basis local_by_uf
"""

import os
import re
import glob
import json
import argparse
import warnings
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import xarray as xr
import geopandas as gpd

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize, TwoSlopeNorm
from matplotlib.lines import Line2D
from scipy.spatial import cKDTree


# ============================================================
# Configuration
# ============================================================

START_YEAR = 1991
END_YEAR = 2020
MONTHS_PT = [
    "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",
    "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro",
]
MONTH_TO_NUM = {m: i + 1 for i, m in enumerate(MONTHS_PT)}

VARIABLES = {
    "TMAX": {
        "file": "Normal-Climatologica-TMAX.xlsx",
        "label": "Maximum temperature",
        "short_label": r"T$_{max}$",
        "unit": "°C",
        "era5_kind": "tmax_dailymax_monthmean",
        "bias_norm": TwoSlopeNorm(vmin=-3.0, vcenter=0.0, vmax=3.0),
        "rmse_norm": Normalize(vmin=0.0, vmax=4.0),
    },
    "TMIN": {
        "file": "Normal-Climatologica-TMIN.xlsx",
        "label": "Minimum temperature",
        "short_label": r"T$_{min}$",
        "unit": "°C",
        "era5_kind": "tmin_dailymin_monthmean",
        "bias_norm": TwoSlopeNorm(vmin=-3.0, vcenter=0.0, vmax=3.0),
        "rmse_norm": Normalize(vmin=0.0, vmax=4.0),
    },
    "TORV": {
        "file": "Normal-Climatologica-TORV.xlsx",
        "label": "Dew-point temperature",
        "short_label": r"T$_d$",
        "unit": "°C",
        "era5_kind": "dewpoint_dailymean_monthmean",
        "bias_norm": TwoSlopeNorm(vmin=-3.0, vcenter=0.0, vmax=3.0),
        "rmse_norm": Normalize(vmin=0.0, vmax=4.0),
    },
    "UR": {
        "file": "Normal-Climatologica-UR.xlsx",
        "label": "Relative humidity",
        "short_label": "RH",
        "unit": "%",
        "era5_kind": "rh_dailymean_monthmean",
        "bias_norm": TwoSlopeNorm(vmin=-20.0, vcenter=0.0, vmax=20.0),
        "rmse_norm": Normalize(vmin=0.0, vmax=25.0),
    },
    "VENTIN": {
        "file": "Normal-Climatologica-VENTIN.xlsx",
        "label": "Wind speed",
        "short_label": "WS",
        "unit": r"m s$^{-1}$",
        "era5_kind": "wind_dailymean_monthmean",
        "bias_norm": TwoSlopeNorm(vmin=-3.0, vcenter=0.0, vmax=3.0),
        "rmse_norm": Normalize(vmin=0.0, vmax=4.0),
    },
    "TMEDUMID": {
        "file": "Normal-Climatologica-TMEDUMID.xlsx",
        "label": "Wet-bulb temperature",
        "short_label": r"T$_{wb}$",
        "unit": "°C",
        "era5_kind": "wetbulb_dailymean_monthmean",
        "bias_norm": TwoSlopeNorm(vmin=-3.0, vcenter=0.0, vmax=3.0),
        "rmse_norm": Normalize(vmin=0.0, vmax=4.0),
    },
}

VAR_ORDER = ["TMAX", "TMIN", "TORV", "UR", "VENTIN", "TMEDUMID"]

UF_TO_REGION = {
    "AC": "North", "AP": "North", "AM": "North", "PA": "North", "RO": "North", "RR": "North", "TO": "North",
    "AL": "Northeast", "BA": "Northeast", "CE": "Northeast", "MA": "Northeast", "PB": "Northeast",
    "PE": "Northeast", "PI": "Northeast", "RN": "Northeast", "SE": "Northeast",
    "DF": "Central-West", "GO": "Central-West", "MT": "Central-West", "MS": "Central-West",
    "ES": "Southeast", "MG": "Southeast", "RJ": "Southeast", "SP": "Southeast",
    "PR": "South", "RS": "South", "SC": "South",
}
REGION_ORDER = ["Brazil", "North", "Northeast", "Central-West", "Southeast", "South"]
REGION_COLORS = {
    "Brazil": "#000000",
    "North": "#1b9e77",
    "Northeast": "#d95f02",
    "Central-West": "#7570b3",
    "Southeast": "#e7298a",
    "South": "#66a61e",
}

UF_UTC_OFFSET_HOURS = {
    # Fixed standard-time approximation. No historical daylight-saving correction.
    "AC": -5, "AM": -4, "RO": -4, "RR": -4, "MT": -4, "MS": -4,
    "AP": -3, "PA": -3, "TO": -3, "MA": -3, "PI": -3, "CE": -3, "RN": -3,
    "PB": -3, "PE": -3, "AL": -3, "SE": -3, "BA": -3, "GO": -3, "DF": -3,
    "MG": -3, "ES": -3, "RJ": -3, "SP": -3, "PR": -3, "SC": -3, "RS": -3,
}

BRAZIL_EXTENT = [-75.5, -32.0, -35.5, 6.5]


# ============================================================
# Helpers
# ============================================================

def ensure_dir(path: str):
    os.makedirs(path, exist_ok=True)


def normalize_name(s: str) -> str:
    s = str(s).strip().lower()
    repl = {
        "á": "a", "à": "a", "â": "a", "ã": "a", "ä": "a",
        "é": "e", "ê": "e", "í": "i", "ó": "o", "ô": "o", "õ": "o",
        "ú": "u", "ç": "c", "º": "", "ª": "",
    }
    for a, b in repl.items():
        s = s.replace(a, b)
    s = re.sub(r"[^a-z0-9]+", "_", s)
    return re.sub(r"_+", "_", s).strip("_")


def normalize_station_code(x) -> Optional[str]:
    if pd.isna(x):
        return None
    s = str(x).strip()
    if not s:
        return None
    # Excel may read code as 83249.0.
    try:
        f = float(s.replace(",", "."))
        if np.isfinite(f) and abs(f - round(f)) < 1e-6:
            return str(int(round(f)))
    except Exception:
        pass
    m = re.search(r"\d+", s)
    return m.group(0) if m else None


def clean_numeric(x):
    if pd.isna(x):
        return np.nan
    if isinstance(x, (int, float, np.integer, np.floating)):
        return float(x)
    s = str(x).strip()
    if s in ["", "-", "–", "--", "nan", "NaN"]:
        return np.nan
    s = s.replace(",", ".")
    s = re.sub(r"[^0-9eE+\-.]", "", s)
    try:
        return float(s)
    except Exception:
        return np.nan


def find_header_row(path: str, required_terms: List[str], max_rows: int = 15) -> int:
    raw = pd.read_excel(path, header=None, nrows=max_rows)
    req = [normalize_name(t) for t in required_terms]
    for i in range(len(raw)):
        vals = [normalize_name(v) for v in raw.iloc[i].tolist()]
        row = " ".join(vals)
        if all(any(r in v for v in vals) or r in row for r in req):
            return i
    return 2


def find_col(columns, candidates: List[str], required: bool = True) -> Optional[str]:
    norm = {normalize_name(c): c for c in columns}
    cand = [normalize_name(c) for c in candidates]
    for cc in cand:
        if cc in norm:
            return norm[cc]
    for c in columns:
        nc = normalize_name(c)
        for cc in cand:
            if cc and (cc in nc or nc in cc):
                return c
    if required:
        raise ValueError(f"Could not find column among {candidates}. Available: {list(columns)}")
    return None


# ============================================================
# INMET climatological normals
# ============================================================

def find_station_file(normal_dir: str) -> str:
    candidates = []
    candidates.extend(glob.glob(os.path.join(normal_dir, "Normal-Climatologica-ESTA*.xlsx")))
    candidates.extend(glob.glob(os.path.join(normal_dir, "*ESTA*.xlsx")))
    if not candidates:
        raise FileNotFoundError(
            "Could not find station metadata file. Expected something like "
            "Normal-Climatologica-ESTAÇÕES.xlsx in --normal_dir."
        )
    return sorted(candidates)[0]


def read_station_metadata(normal_dir: str) -> pd.DataFrame:
    path = find_station_file(normal_dir)
    header = find_header_row(path, ["Código", "Latitude", "Longitude"])
    df = pd.read_excel(path, header=header)
    df.columns = [str(c).strip() for c in df.columns]

    code_col = find_col(df.columns, ["Código", "Codigo", "Cod"], True)
    name_col = find_col(df.columns, ["Nome da Estação", "Nome da Estacao", "Estação", "Estacao"], False)
    uf_col = find_col(df.columns, ["UF"], True)
    lat_col = find_col(df.columns, ["Latitude"], True)
    lon_col = find_col(df.columns, ["Longitude"], True)
    alt_col = find_col(df.columns, ["Altitude"], False)
    status_col = find_col(df.columns, ["Situação", "Situacao"], False)

    out = pd.DataFrame({
        "station_id": df[code_col].map(normalize_station_code),
        "station_name": df[name_col].astype(str).str.strip() if name_col else "",
        "uf": df[uf_col].astype(str).str.upper().str.extract(r"([A-Z]{2})")[0],
        "lat": df[lat_col].map(clean_numeric),
        "lon": df[lon_col].map(clean_numeric),
        "altitude_m": df[alt_col].map(clean_numeric) if alt_col else np.nan,
        "status": df[status_col].astype(str).str.strip() if status_col else "",
    })
    out = out.dropna(subset=["station_id", "uf", "lat", "lon"])
    out = out[out["uf"].isin(UF_TO_REGION)].copy()
    out["region"] = out["uf"].map(UF_TO_REGION)
    out = out.drop_duplicates(subset=["station_id", "uf"], keep="first").reset_index(drop=True)
    print(f"[INFO] Station metadata: {len(out)} stations from {Path(path).name}")
    return out


def read_normal_variable_file(path: str, variable: str) -> pd.DataFrame:
    header = find_header_row(path, ["Código", "Janeiro", "Dezembro"])
    df = pd.read_excel(path, header=header)
    df.columns = [str(c).strip() for c in df.columns]

    code_col = find_col(df.columns, ["Código", "Codigo", "Cod"], True)
    name_col = find_col(df.columns, ["Nome da Estação", "Nome da Estacao", "Estação", "Estacao"], False)
    uf_col = find_col(df.columns, ["UF"], True)

    month_cols = []
    for m in MONTHS_PT:
        col = find_col(df.columns, [m], required=False)
        if col is not None:
            month_cols.append((m, col))
    if len(month_cols) < 6:
        raise ValueError(f"Too few month columns detected in {path}: {month_cols}")

    rows = []
    for _, r in df.iterrows():
        sid = normalize_station_code(r[code_col])
        if sid is None:
            continue
        uf = str(r[uf_col]).upper().strip()
        uf_match = re.search(r"([A-Z]{2})", uf)
        uf = uf_match.group(1) if uf_match else uf
        for m_name, col in month_cols:
            val = clean_numeric(r[col])
            if np.isfinite(val):
                rows.append({
                    "station_id": sid,
                    "station_name_inmet": str(r[name_col]).strip() if name_col else "",
                    "uf": uf,
                    "variable": variable,
                    "month": MONTH_TO_NUM[m_name],
                    "month_name": m_name,
                    "inmet_normal": float(val),
                })
    out = pd.DataFrame(rows)
    print(f"[INFO] INMET normals {variable}: {len(out)} station-month rows from {Path(path).name}")
    return out


def read_all_inmet_normals(normal_dir: str, stations: pd.DataFrame) -> pd.DataFrame:
    frames = []
    for var in VAR_ORDER:
        path = os.path.join(normal_dir, VARIABLES[var]["file"])
        if not os.path.exists(path):
            raise FileNotFoundError(f"Missing required normal file for {var}: {path}")
        frames.append(read_normal_variable_file(path, var))

    normals = pd.concat(frames, ignore_index=True)
    normals = normals.merge(
        stations[["station_id", "uf", "station_name", "lat", "lon", "altitude_m", "status", "region"]],
        on=["station_id", "uf"],
        how="inner",
    )
    normals = normals.dropna(subset=["lat", "lon", "inmet_normal"])
    print(f"[INFO] INMET normals matched to station coordinates: {len(normals)} rows")
    return normals


# ============================================================
# ERA5 processing
# ============================================================

def standardize_lat_lon_time(ds: xr.Dataset) -> xr.Dataset:
    rename = {}
    for t in ["time", "valid_time", "datetime", "date"]:
        if t in ds.coords or t in ds.dims:
            if t != "time": rename[t] = "time"
            break
    for la in ["latitude", "lat", "LAT", "Latitude", "y"]:
        if la in ds.coords or la in ds.dims:
            if la != "lat": rename[la] = "lat"
            break
    for lo in ["longitude", "lon", "LON", "Longitude", "x"]:
        if lo in ds.coords or lo in ds.dims:
            if lo != "lon": rename[lo] = "lon"
            break
    if rename:
        ds = ds.rename(rename)
    if "time" not in ds.coords or "lat" not in ds.coords or "lon" not in ds.coords:
        raise ValueError(f"ERA5 dataset missing required coordinates. Coords: {list(ds.coords)}")
    ds["time"] = pd.to_datetime(ds["time"].values)
    if float(ds["lon"].max()) > 180:
        ds = ds.assign_coords(lon=((ds["lon"] + 180) % 360) - 180).sortby("lon")
    if ds["lat"].values[0] > ds["lat"].values[-1]:
        ds = ds.sortby("lat")
    return ds


def find_variable(ds: xr.Dataset, candidates: List[str], required: bool = True) -> Optional[str]:
    lower = {v.lower(): v for v in ds.data_vars}
    norm = {normalize_name(v): v for v in ds.data_vars}
    for c in candidates:
        if c in ds.data_vars:
            return c
        if c.lower() in lower:
            return lower[c.lower()]
        nc = normalize_name(c)
        if nc in norm:
            return norm[nc]
    for c in candidates:
        nc = normalize_name(c)
        for nv, original in norm.items():
            if nc and (nc in nv or nv in nc):
                return original
    if required:
        raise ValueError(f"Could not find ERA5 variable among {candidates}. Available: {list(ds.data_vars)}")
    return None


def reduce_to_time_lat_lon(da: xr.DataArray) -> xr.DataArray:
    keep = {"time", "lat", "lon"}
    for dim in list(da.dims):
        if dim not in keep:
            if da.sizes[dim] == 1:
                da = da.isel({dim: 0})
            else:
                da = da.mean(dim=dim, skipna=True)
    return da


def maybe_kelvin_to_celsius(da: xr.DataArray) -> xr.DataArray:
    med = float(np.nanmedian(da.values))
    if np.isfinite(med) and med > 100:
        return da - 273.15
    return da


def saturation_vapour_pressure_hpa(temp_c):
    return 6.112 * np.exp((17.67 * temp_c) / (temp_c + 243.5))


def compute_rh_percent(t_c, td_c):
    es = saturation_vapour_pressure_hpa(t_c)
    ea = saturation_vapour_pressure_hpa(td_c)
    return np.clip(100.0 * ea / es, 0.0, 100.0)


def compute_wetbulb_stull(t_c, rh_pct):
    rh = np.clip(rh_pct, 1.0, 100.0)
    tw = (
        t_c * np.arctan(0.151977 * np.sqrt(rh + 8.313659))
        + np.arctan(t_c + rh)
        - np.arctan(rh - 1.676331)
        + 0.00391838 * rh ** 1.5 * np.arctan(0.023101 * rh)
        - 4.686035
    )
    return tw


def resolve_era5_files(pattern: str) -> List[str]:
    files = sorted(glob.glob(pattern))
    selected = []
    for f in files:
        m = re.search(r"(19|20)\d{2}", Path(f).name)
        if m:
            y = int(m.group(0))
            if START_YEAR <= y <= END_YEAR:
                selected.append(f)
        else:
            selected.append(f)
    if not selected:
        raise FileNotFoundError(f"No ERA5 files overlapping {START_YEAR}-{END_YEAR}: {pattern}")
    return selected


def get_station_grid_indices(ds: xr.Dataset, stations: pd.DataFrame) -> pd.DataFrame:
    lats = ds["lat"].values
    lons = ds["lon"].values
    lon2d, lat2d = np.meshgrid(lons, lats)
    tree = cKDTree(np.column_stack([lat2d.ravel(), lon2d.ravel()]))
    rows = []
    for _, st in stations.iterrows():
        dist, flat_idx = tree.query([st["lat"], st["lon"]])
        iy, ix = np.unravel_index(flat_idx, lat2d.shape)
        rows.append({
            "station_id": str(st["station_id"]),
            "uf": st["uf"],
            "region": st.get("region", UF_TO_REGION.get(st["uf"])),
            "lat": float(st["lat"]),
            "lon": float(st["lon"]),
            "iy": int(iy),
            "ix": int(ix),
            "era5_lat": float(lats[iy]),
            "era5_lon": float(lons[ix]),
            "era5_grid_distance_deg": float(dist),
        })
    return pd.DataFrame(rows)


def year_from_path(path: str) -> str:
    m = re.search(r"(19|20)\d{2}", Path(path).name)
    return m.group(0) if m else Path(path).stem


def aggregate_station_monthly_from_hourly(
    time_index: pd.DatetimeIndex,
    station_meta: pd.DataFrame,
    arrays: Dict[str, np.ndarray],
    daily_time_basis: str,
) -> pd.DataFrame:
    """Aggregate hourly station arrays to monthly values.

    arrays must contain 2-D numpy arrays with shape (time, station):
      t_c, td_c, rh, twb, ws
    """
    station_ids = station_meta["station_id"].astype(str).values
    out_frames = []

    if daily_time_basis == "utc":
        groups = [("ALL", station_meta.index.to_numpy(), 0)]
    elif daily_time_basis == "local_by_uf":
        groups = []
        for uf, sub in station_meta.groupby("uf"):
            offset = UF_UTC_OFFSET_HOURS.get(uf, -3)
            groups.append((uf, sub.index.to_numpy(), offset))
    else:
        raise ValueError("daily_time_basis must be 'utc' or 'local_by_uf'")

    for _, idx, offset in groups:
        if len(idx) == 0:
            continue
        local_time = time_index + pd.Timedelta(hours=offset)

        def wide(arr):
            return pd.DataFrame(arr[:, idx], index=local_time, columns=station_ids[idx])

        t = wide(arrays["t_c"])
        td = wide(arrays["td_c"])
        rh = wide(arrays["rh"])
        twb = wide(arrays["twb"])
        ws = wide(arrays["ws"])

        daily = {
            "TMAX": t.resample("D").max(),
            "TMIN": t.resample("D").min(),
            "TORV": td.resample("D").mean(),
            "UR": rh.resample("D").mean(),
            "VENTIN": ws.resample("D").mean(),
            "TMEDUMID": twb.resample("D").mean(),
        }

        for var, df_daily in daily.items():
            monthly = df_daily.resample("MS").mean()
            n_days = df_daily.resample("MS").count()
            long_val = monthly.stack(dropna=False).rename("era5_value").reset_index()
            long_val.columns = ["date", "station_id", "era5_value"]
            long_n = n_days.stack(dropna=False).rename("n_daily_values_era5").reset_index()
            long_n.columns = ["date", "station_id", "n_daily_values_era5"]
            long = long_val.merge(long_n, on=["date", "station_id"], how="left")
            long["variable"] = var
            long["year"] = pd.to_datetime(long["date"]).dt.year
            long["month"] = pd.to_datetime(long["date"]).dt.month
            out_frames.append(long[["station_id", "variable", "year", "month", "era5_value", "n_daily_values_era5"]])

    if not out_frames:
        return pd.DataFrame(columns=["station_id", "variable", "year", "month", "era5_value", "n_daily_values_era5"])
    return pd.concat(out_frames, ignore_index=True)


def process_era5_year(
    file_path: str,
    stations: pd.DataFrame,
    grid_index: Optional[pd.DataFrame],
    daily_time_basis: str,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    print(f"[INFO] ERA5 hourly file: {Path(file_path).name}")
    ds = xr.open_dataset(file_path)
    ds = standardize_lat_lon_time(ds)
    ds = ds.sel(time=slice(f"{START_YEAR}-01-01", f"{END_YEAR}-12-31"))
    if ds.sizes.get("time", 0) == 0:
        ds.close()
        return pd.DataFrame(), grid_index

    if grid_index is None:
        grid_index = get_station_grid_indices(ds, stations)
        print(f"[INFO] ERA5 nearest grid cells prepared for {len(grid_index)} stations")

    tvar = find_variable(ds, ["t2m", "2t", "T2M", "T2", "var167", "2m_temperature"], True)
    tdvar = find_variable(ds, ["d2m", "2d", "D2M", "var168", "2m_dewpoint_temperature"], True)
    uvar = find_variable(ds, ["u10", "10u", "U10", "var165", "10m_u_component_of_wind"], True)
    vvar = find_variable(ds, ["v10", "10v", "V10", "var166", "10m_v_component_of_wind"], True)
    print(f"[INFO] ERA5 variables: T={tvar}, Td={tdvar}, U={uvar}, V={vvar}")

    station_dim = "station"
    iy = xr.DataArray(grid_index["iy"].to_numpy(), dims=station_dim)
    ix = xr.DataArray(grid_index["ix"].to_numpy(), dims=station_dim)

    t_c = maybe_kelvin_to_celsius(reduce_to_time_lat_lon(ds[tvar])).isel(lat=iy, lon=ix).values.astype(np.float32)
    td_c = maybe_kelvin_to_celsius(reduce_to_time_lat_lon(ds[tdvar])).isel(lat=iy, lon=ix).values.astype(np.float32)
    u = reduce_to_time_lat_lon(ds[uvar]).isel(lat=iy, lon=ix).values.astype(np.float32)
    v = reduce_to_time_lat_lon(ds[vvar]).isel(lat=iy, lon=ix).values.astype(np.float32)
    ws = np.sqrt(u ** 2 + v ** 2).astype(np.float32)
    rh = compute_rh_percent(t_c, td_c).astype(np.float32)
    twb = compute_wetbulb_stull(t_c, rh).astype(np.float32)

    station_meta = grid_index.reset_index(drop=True).copy()
    station_meta.index = np.arange(len(station_meta))
    time_index = pd.DatetimeIndex(pd.to_datetime(ds["time"].values))
    monthly = aggregate_station_monthly_from_hourly(
        time_index=time_index,
        station_meta=station_meta,
        arrays={"t_c": t_c, "td_c": td_c, "rh": rh, "twb": twb, "ws": ws},
        daily_time_basis=daily_time_basis,
    )

    ds.close()
    return monthly, grid_index


def dewpoint_from_t_rh(t_c, rh_pct):
    """Approximate dew-point temperature [°C] from air temperature [°C] and RH [%]."""
    rh = np.clip(np.asarray(rh_pct, dtype=float), 1e-3, 100.0)
    t = np.asarray(t_c, dtype=float)
    gamma = np.log(rh / 100.0) + (17.27 * t) / (237.3 + t)
    return (237.3 * gamma) / (17.27 - gamma)


def find_daily_era5_files(daily_dir: str) -> List[str]:
    patterns = [
        os.path.join(daily_dir, "ERA5_daily_Brazil_*.nc"),
        os.path.join(daily_dir, "*daily*Brazil*.nc"),
    ]
    files = []
    for pat in patterns:
        files.extend(glob.glob(pat))
    files = sorted(set(files))
    selected = []
    for f in files:
        m = re.search(r"(19|20)\d{2}", Path(f).name)
        if m:
            y = int(m.group(0))
            if START_YEAR <= y <= END_YEAR:
                selected.append(f)
    if not selected:
        raise FileNotFoundError(
            f"No preprocessed daily ERA5 files for {START_YEAR}-{END_YEAR} were found in: {daily_dir}"
        )
    return selected


def select_daily_var(ds: xr.Dataset, candidates: List[str], required: bool = True) -> xr.DataArray:
    name = find_variable(ds, candidates, required=required)
    return reduce_to_time_lat_lon(ds[name])


def process_era5_daily_year_fast(
    file_path: str,
    stations: pd.DataFrame,
    grid_index: Optional[pd.DataFrame],
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Fast station-month extraction from preprocessed daily ERA5 files.

    This avoids re-reading the full hourly ERA5 archive. It is the recommended
    mode for the 1991-2020 normal-climatology validation because Figure 1 already
    produced daily ERA5 fields on the same baseline period used for heatwave
    thresholds.
    """
    print(f"[INFO] ERA5 daily file: {Path(file_path).name}")
    ds = xr.open_dataset(file_path)
    ds = standardize_lat_lon_time(ds)
    ds = ds.sel(time=slice(f"{START_YEAR}-01-01", f"{END_YEAR}-12-31"))
    if ds.sizes.get("time", 0) == 0:
        ds.close()
        return pd.DataFrame(), grid_index

    if grid_index is None:
        grid_index = get_station_grid_indices(ds, stations)
        print(f"[INFO] ERA5 nearest grid cells prepared for {len(grid_index)} stations")

    station_dim = "station"
    iy = xr.DataArray(grid_index["iy"].to_numpy(), dims=station_dim)
    ix = xr.DataArray(grid_index["ix"].to_numpy(), dims=station_dim)

    # Daily variables from the Figure 1 preprocessing workflow.
    # TMAX/TMIN/TMEDUMID/UR/VENTIN are read directly when available.
    # TORV is reconstructed from daily mean T and RH if daily dew point is absent.
    tmean_da = select_daily_var(ds, ["Tmean", "tmean", "T2mean", "t2m_mean"], required=True)
    rh_da = select_daily_var(ds, ["RHmean", "rhmean", "RH", "relative_humidity"], required=True)

    tmax = select_daily_var(ds, ["Tmax", "tmax", "T2max", "t2m_max"], True).isel(lat=iy, lon=ix).values.astype(np.float32)
    tmin = select_daily_var(ds, ["Tmin", "tmin", "T2min", "t2m_min"], True).isel(lat=iy, lon=ix).values.astype(np.float32)
    tmean = tmean_da.isel(lat=iy, lon=ix).values.astype(np.float32)
    rh = rh_da.isel(lat=iy, lon=ix).values.astype(np.float32)

    twb_name = find_variable(ds, ["Twbmean", "twbmean", "Twb", "wetbulb"], required=False)
    if twb_name is not None:
        twb = reduce_to_time_lat_lon(ds[twb_name]).isel(lat=iy, lon=ix).values.astype(np.float32)
    else:
        twb = compute_wetbulb_stull(tmean, rh).astype(np.float32)

    ws_name = find_variable(ds, ["WS10mean", "ws10mean", "wind_speed", "WS10"], required=False)
    if ws_name is not None:
        ws = reduce_to_time_lat_lon(ds[ws_name]).isel(lat=iy, lon=ix).values.astype(np.float32)
    else:
        u_name = find_variable(ds, ["u10", "U10", "var165"], required=True)
        v_name = find_variable(ds, ["v10", "V10", "var166"], required=True)
        u = reduce_to_time_lat_lon(ds[u_name]).isel(lat=iy, lon=ix).values.astype(np.float32)
        v = reduce_to_time_lat_lon(ds[v_name]).isel(lat=iy, lon=ix).values.astype(np.float32)
        ws = np.sqrt(u**2 + v**2).astype(np.float32)

    td_name = find_variable(ds, ["Tdmean", "TDmean", "D2mean", "d2m_mean", "TORV", "dewpoint_mean"], required=False)
    if td_name is not None:
        td = maybe_kelvin_to_celsius(reduce_to_time_lat_lon(ds[td_name])).isel(lat=iy, lon=ix).values.astype(np.float32)
    else:
        td = dewpoint_from_t_rh(tmean, rh).astype(np.float32)

    time_index = pd.DatetimeIndex(pd.to_datetime(ds["time"].values))
    station_ids = grid_index["station_id"].astype(str).values

    def monthly_long(arr: np.ndarray, var: str) -> pd.DataFrame:
        wide = pd.DataFrame(arr, index=time_index, columns=station_ids)
        monthly = wide.resample("MS").mean()
        n_days = wide.resample("MS").count()
        try:
            long_val = monthly.stack(future_stack=True).rename("era5_value").reset_index()
            long_n = n_days.stack(future_stack=True).rename("n_daily_values_era5").reset_index()
        except TypeError:
            long_val = monthly.stack(dropna=False).rename("era5_value").reset_index()
            long_n = n_days.stack(dropna=False).rename("n_daily_values_era5").reset_index()
        long_val.columns = ["date", "station_id", "era5_value"]
        long_n.columns = ["date", "station_id", "n_daily_values_era5"]
        out = long_val.merge(long_n, on=["date", "station_id"], how="left")
        out["variable"] = var
        out["year"] = pd.to_datetime(out["date"]).dt.year
        out["month"] = pd.to_datetime(out["date"]).dt.month
        return out[["station_id", "variable", "year", "month", "era5_value", "n_daily_values_era5"]]

    out = pd.concat([
        monthly_long(tmax, "TMAX"),
        monthly_long(tmin, "TMIN"),
        monthly_long(td, "TORV"),
        monthly_long(rh, "UR"),
        monthly_long(ws, "VENTIN"),
        monthly_long(twb, "TMEDUMID"),
    ], ignore_index=True)

    ds.close()
    return out, grid_index


def build_era5_monthly_climatology(
    era5_glob: str,
    stations: pd.DataFrame,
    out_dir: str,
    daily_time_basis: str,
    reuse_cache: bool,
    max_years_per_run: Optional[int] = None,
    build_cache_only: bool = False,
    era5_daily_dir: Optional[str] = None,
    source: str = "auto",
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Build ERA5 station-month climatology.

    Preferred mode is `source=daily`, using daily ERA5 files already produced by
    the Figure 1 workflow. This is much faster than processing the 30-year hourly
    archive and is scientifically aligned with the threshold baseline. Hourly mode
    remains available for exact local-day aggregation, but it is much slower.
    """
    ensure_dir(out_dir)

    if source not in ["auto", "daily", "hourly"]:
        raise ValueError("--source must be 'auto', 'daily' or 'hourly'")

    daily_files = []
    if era5_daily_dir:
        try:
            daily_files = find_daily_era5_files(era5_daily_dir)
        except Exception as exc:
            if source == "daily":
                raise
            print(f"[WARN] Daily ERA5 files not usable: {exc}")

    use_daily = source == "daily" or (source == "auto" and len(daily_files) > 0)

    if use_daily:
        files = daily_files
        # Preprocessed daily fields retain the calendar definition used when
        # they were generated. A local-day shift cannot be reconstructed from
        # daily files alone.
        if daily_time_basis == "local_by_uf":
            print(
                "[INFO] Daily ERA5 mode uses the calendar definition already "
                "stored in the daily files; local-day shifting is applied only "
                "in hourly mode."
            )
        tag = "DailyFast"
        processor = lambda f, gi: process_era5_daily_year_fast(f, stations, gi)
    else:
        if not era5_glob:
            raise ValueError(
                "Hourly ERA5 input is required because daily files were not "
                "selected or available."
            )
        files = resolve_era5_files(era5_glob)
        tag = "UTCmonth" if daily_time_basis == "utc" else "LocalUFmonth"
        processor = lambda f, gi: process_era5_year(
            f, stations, gi, daily_time_basis
        )

    cache_grid = os.path.join(out_dir, f"CACHE_ERA5_normals_station_grid_index_{tag}.csv")
    cache_all = os.path.join(out_dir, f"CACHE_ERA5_station_monthly_climatology_1991_2020_{tag}.csv")

    if reuse_cache and os.path.exists(cache_all) and os.path.exists(cache_grid) and not build_cache_only:
        print(f"[INFO] Reusing combined ERA5 monthly climatology cache: {Path(cache_all).name}")
        clim = pd.read_csv(cache_all)
        grid_index = pd.read_csv(cache_grid)
        clim["station_id"] = clim["station_id"].astype(str)
        grid_index["station_id"] = grid_index["station_id"].astype(str)
        return clim, grid_index

    grid_index = None
    if reuse_cache and os.path.exists(cache_grid):
        grid_index = pd.read_csv(cache_grid)
        grid_index["station_id"] = grid_index["station_id"].astype(str)
        print(f"[INFO] Reusing ERA5 station grid-index cache: {Path(cache_grid).name}")

    all_yearly = []
    processed_this_run = 0

    for i, f in enumerate(files, 1):
        year_label = year_from_path(f)
        cache_year = os.path.join(out_dir, f"CACHE_ERA5_station_monthly_{year_label}_{tag}.csv")
        tmp_year = cache_year + ".tmp"

        if reuse_cache and os.path.exists(cache_year):
            print(f"[SKIP] Reusing cached ERA5 station-monthly file {i}/{len(files)}: {Path(cache_year).name}")
            dfy = pd.read_csv(cache_year)
            dfy["station_id"] = dfy["station_id"].astype(str)
            all_yearly.append(dfy)
            continue

        if max_years_per_run is not None and processed_this_run >= max_years_per_run:
            print(f"[STOP] Reached --max_years_per_run={max_years_per_run}. Re-run to continue.")
            continue

        print(f"[INFO] Processing ERA5 file {i}/{len(files)}")
        dfy, grid_index = processor(f, grid_index)
        if grid_index is not None:
            grid_index.to_csv(cache_grid, index=False)
        if not dfy.empty:
            dfy.to_csv(tmp_year, index=False)
            os.replace(tmp_year, cache_year)
            print(f"[OK] Cached ERA5 station-monthly year: {cache_year}")
            all_yearly.append(dfy)
        processed_this_run += 1

    if build_cache_only:
        print("[DONE] Cache-building mode requested. Metrics/figures were not generated.")
        return pd.DataFrame(), grid_index

    if not all_yearly:
        raise RuntimeError("No ERA5 station-monthly data available. Build or reuse yearly caches first.")

    monthly = pd.concat(all_yearly, ignore_index=True)
    monthly = monthly[(monthly["year"] >= START_YEAR) & (monthly["year"] <= END_YEAR)].copy()
    monthly["station_id"] = monthly["station_id"].astype(str)
    monthly["era5_value"] = pd.to_numeric(monthly["era5_value"], errors="coerce")

    clim = (
        monthly.dropna(subset=["era5_value"])
        .groupby(["station_id", "variable", "month"], as_index=False)
        .agg(
            era5_climatology=("era5_value", "mean"),
            n_year_months_era5=("era5_value", "count"),
            n_daily_values_era5=("n_daily_values_era5", "sum"),
        )
    )
    clim.to_csv(cache_all, index=False)
    print(f"[OK] Cached ERA5 monthly climatology: {cache_all}")
    return clim, grid_index


# ============================================================
# Metrics and Taylor diagrams
# ============================================================

def station_metric_table(paired: pd.DataFrame, min_months: int) -> pd.DataFrame:
    rows = []
    for (sid, var), g in paired.groupby(["station_id", "variable"]):
        obs = pd.to_numeric(g["inmet_normal"], errors="coerce").to_numpy(float)
        mod = pd.to_numeric(g["era5_climatology"], errors="coerce").to_numpy(float)
        ok = np.isfinite(obs) & np.isfinite(mod)
        obs = obs[ok]
        mod = mod[ok]
        if len(obs) < min_months:
            continue
        if np.nanstd(obs) > 0 and np.nanstd(mod) > 0 and len(obs) >= 2:
            r = float(np.corrcoef(obs, mod)[0, 1])
        else:
            r = np.nan
        diff = mod - obs
        rows.append({
            "station_id": sid,
            "variable": var,
            "pearson_r": r,
            "rmse": float(np.sqrt(np.nanmean(diff ** 2))),
            "bias_era5_minus_inmet": float(np.nanmean(diff)),
            "mae": float(np.nanmean(np.abs(diff))),
            "n_months": int(len(obs)),
            "obs_mean": float(np.nanmean(obs)),
            "era5_mean": float(np.nanmean(mod)),
            "obs_std": float(np.nanstd(obs, ddof=1)) if len(obs) > 1 else np.nan,
            "era5_std": float(np.nanstd(mod, ddof=1)) if len(mod) > 1 else np.nan,
        })
    metrics = pd.DataFrame(rows)
    meta_cols = ["station_id", "uf", "station_name", "lat", "lon", "altitude_m", "status", "region"]
    meta = paired[meta_cols].drop_duplicates(subset=["station_id"])
    metrics = metrics.merge(meta, on="station_id", how="left")
    return metrics


def paired_arrays_for_group(paired: pd.DataFrame, variable: str, region: str) -> Tuple[np.ndarray, np.ndarray]:
    d = paired[paired["variable"] == variable].copy()
    if region != "Brazil":
        d = d[d["region"] == region].copy()
    obs = pd.to_numeric(d["inmet_normal"], errors="coerce").to_numpy(float)
    mod = pd.to_numeric(d["era5_climatology"], errors="coerce").to_numpy(float)
    ok = np.isfinite(obs) & np.isfinite(mod)
    return obs[ok], mod[ok]


def compute_taylor_metrics(paired: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for var in VAR_ORDER:
        for region in REGION_ORDER:
            obs, mod = paired_arrays_for_group(paired, var, region)
            if len(obs) < 8 or np.nanstd(obs, ddof=1) == 0 or np.nanstd(mod, ddof=1) == 0:
                corr = std_norm = rmse_norm = crmse_norm = np.nan
            else:
                corr = float(np.corrcoef(obs, mod)[0, 1])
                std_norm = float(np.nanstd(mod, ddof=1) / np.nanstd(obs, ddof=1))
                rmse_norm = float(np.sqrt(np.nanmean((mod - obs) ** 2)) / np.nanstd(obs, ddof=1))
                obs_anom = obs - np.nanmean(obs)
                mod_anom = mod - np.nanmean(mod)
                crmse_norm = float(np.sqrt(np.nanmean((mod_anom - obs_anom) ** 2)) / np.nanstd(obs, ddof=1))
            rows.append({
                "variable": var,
                "region": region,
                "n_pairs": int(len(obs)),
                "corr": corr,
                "std_norm": std_norm,
                "rmse_norm": rmse_norm,
                "crmse_norm": crmse_norm,
            })
    return pd.DataFrame(rows)


# ============================================================
# Output writers
# ============================================================

def save_outputs(
    paired: pd.DataFrame,
    station_metrics: pd.DataFrame,
    taylor_df: pd.DataFrame,
    stations: pd.DataFrame,
    grid_index: Optional[pd.DataFrame],
    out_dir: str,
    metadata: Dict,
):
    """Save all validation tables and metadata.

    Table output is written independently of the plotting stage.
    """
    ensure_dir(out_dir)

    paths = {
        "paired": os.path.join(out_dir, "Supplementary_Table_ERA5_INMET_climatological_normals_station_month_pairs_1991_2020.csv"),
        "station_metrics": os.path.join(out_dir, "Supplementary_Table_ERA5_INMET_climatological_normals_station_metrics_1991_2020.csv"),
        "taylor": os.path.join(out_dir, "Supplementary_Table_ERA5_INMET_climatological_normals_taylor_metrics_1991_2020.csv"),
        "stations": os.path.join(out_dir, "Supplementary_Table_INMET_climatological_normal_station_metadata.csv"),
        "grid_index": os.path.join(out_dir, "Supplementary_Table_ERA5_INMET_climatological_normals_nearest_grid_index.csv"),
        "xlsx": os.path.join(out_dir, "Supplementary_Tables_ERA5_INMET_climatological_normals_validation_1991_2020.xlsx"),
        "metadata": os.path.join(out_dir, "software_metadata_climatological_normals_validation.json"),
    }

    paired.to_csv(paths["paired"], index=False)
    station_metrics.to_csv(paths["station_metrics"], index=False)
    taylor_df.to_csv(paths["taylor"], index=False)
    stations.to_csv(paths["stations"], index=False)

    if grid_index is not None and not grid_index.empty:
        grid_index.to_csv(paths["grid_index"], index=False)

    # Excel workbook with short sheet names for compatibility.
    with pd.ExcelWriter(paths["xlsx"]) as writer:
        paired.to_excel(writer, sheet_name="station_month_pairs", index=False)
        station_metrics.to_excel(writer, sheet_name="station_metrics", index=False)
        taylor_df.to_excel(writer, sheet_name="taylor_metrics", index=False)
        stations.to_excel(writer, sheet_name="station_metadata", index=False)
        if grid_index is not None and not grid_index.empty:
            grid_index.to_excel(writer, sheet_name="nearest_grid", index=False)

    with open(paths["metadata"], "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2, ensure_ascii=False)

    for key, path in paths.items():
        if key == "grid_index" and (grid_index is None or grid_index.empty):
            continue
        print(f"[OK] Saved: {path}")

# ============================================================
# Shapefile handling and plotting
# ============================================================

def read_states_shapefile(path: str) -> gpd.GeoDataFrame:
    if not os.path.exists(path):
        raise FileNotFoundError(f"State shapefile not found: {path}")
    gdf = gpd.read_file(path)
    gdf = gdf.to_crs("EPSG:4326") if gdf.crs is not None else gdf.set_crs("EPSG:4326")

    state_name_to_uf = {
        "ACRE": "AC", "ALAGOAS": "AL", "AMAPA": "AP", "AMAPÁ": "AP", "AMAZONAS": "AM",
        "BAHIA": "BA", "CEARA": "CE", "CEARÁ": "CE", "DISTRITO FEDERAL": "DF",
        "ESPIRITO SANTO": "ES", "ESPÍRITO SANTO": "ES", "GOIAS": "GO", "GOIÁS": "GO",
        "MARANHAO": "MA", "MARANHÃO": "MA", "MATO GROSSO": "MT", "MATO GROSSO DO SUL": "MS",
        "MINAS GERAIS": "MG", "PARA": "PA", "PARÁ": "PA", "PARAIBA": "PB", "PARAÍBA": "PB",
        "PARANA": "PR", "PARANÁ": "PR", "PERNAMBUCO": "PE", "PIAUI": "PI", "PIAUÍ": "PI",
        "RIO DE JANEIRO": "RJ", "RIO GRANDE DO NORTE": "RN", "RIO GRANDE DO SUL": "RS",
        "RONDONIA": "RO", "RONDÔNIA": "RO", "RORAIMA": "RR", "SANTA CATARINA": "SC",
        "SAO PAULO": "SP", "SÃO PAULO": "SP", "SERGIPE": "SE", "TOCANTINS": "TO",
    }
    state_name_to_uf_norm = {normalize_name(k): v for k, v in state_name_to_uf.items()}

    uf_col = None
    for c in gdf.columns:
        cl = normalize_name(c)
        if cl in ["uf", "sigla", "sigla_uf", "uf_05", "sigla_uf_05"]:
            vals = gdf[c].astype(str).str.upper().str.extract(r"([A-Z]{2})")[0]
            if vals.isin(list(UF_TO_REGION.keys())).sum() >= 10:
                gdf["uf"] = vals
                uf_col = c
                break
    if uf_col is None:
        for c in gdf.columns:
            if c == "geometry":
                continue
            vals = gdf[c].astype(str).map(normalize_name)
            if vals.isin(state_name_to_uf_norm.keys()).sum() >= 10:
                gdf["uf"] = vals.map(state_name_to_uf_norm)
                uf_col = c
                break
    if uf_col is None:
        raise ValueError(f"Could not identify UF or state-name column in {path}. Columns: {list(gdf.columns)}")
    gdf = gdf[gdf["uf"].isin(UF_TO_REGION)].copy()
    gdf = gdf[["uf", "geometry"]].dissolve(by="uf", as_index=False)
    return gdf


def point_size_from_n(n):
    """Return conservative marker sizes for station maps.

    Marker size represents station sample size while limiting visual overlap.
    """
    n = np.asarray(n, float)
    if len(n) == 0 or not np.isfinite(n).any():
        return np.full_like(n, 18.0, dtype=float)
    lo, hi = np.nanpercentile(n, [5, 95])
    if hi <= lo:
        return np.full_like(n, 20.0, dtype=float)
    return 10.0 + 28.0 * np.clip((n - lo) / (hi - lo), 0, 1)


def format_map_axis(ax, states, row_idx=None, col_idx=None):
    """Format Brazil station-map panels with compact, non-overlapping labels."""
    states.boundary.plot(ax=ax, color="0.35", linewidth=0.35, zorder=2)
    ax.set_xlim(BRAZIL_EXTENT[0], BRAZIL_EXTENT[1])
    ax.set_ylim(BRAZIL_EXTENT[2], BRAZIL_EXTENT[3])
    ax.grid(True, linestyle="--", linewidth=0.22, alpha=0.22)

    # Keep geographic information but avoid repeating large axis labels in every panel.
    ax.set_xlabel("Longitude" if row_idx == 2 else "", fontsize=12, labelpad=1.5)
    ax.set_ylabel("Latitude" if col_idx == 0 else "", fontsize=12, labelpad=1.5)
    ax.tick_params(labelsize=7, direction="in", length=3, width=0.55)

    if row_idx is not None and row_idx < 2:
        ax.set_xticklabels([])
    if col_idx is not None and col_idx > 0:
        ax.set_yticklabels([])


def setup_taylor_axis(ax, title: str):
    ax.set_theta_zero_location("E")
    ax.set_theta_direction(1)
    ax.set_thetamin(0)
    ax.set_thetamax(90)
    ax.set_rlim(0, 2.0)

    corr_ticks = np.array([0.0, 0.2, 0.4, 0.6, 0.8, 0.9, 0.95, 0.99, 1.0])
    theta_ticks = np.degrees(np.arccos(corr_ticks))
    ax.set_thetagrids(theta_ticks, labels=[f"{c:g}" for c in corr_ticks], fontsize=12)
    ax.set_rgrids([0.5, 1.0, 1.5, 2.0], angle=135, fontsize=12)
    ax.grid(True, linestyle="--", alpha=0.40, linewidth=0.45)

    theta = np.linspace(0, np.pi / 2, 200)
    ax.plot(theta, np.ones_like(theta), "k--", lw=0.9, alpha=0.65)
    ax.plot(0, 1, marker="*", color="black", markersize=8, linestyle="None")
    ax.set_title(title, fontsize=13, fontweight="bold", pad=9)


def plot_taylor_points(ax, taylor_df: pd.DataFrame, variable: str):
    sub = taylor_df[taylor_df["variable"] == variable]
    for _, r in sub.iterrows():
        region = r["region"]
        corr = r["corr"]
        stdn = r["std_norm"]
        if not np.isfinite(corr) or not np.isfinite(stdn):
            continue
        theta = np.arccos(np.clip(corr, 0.0, 1.0))
        marker = "*" if region == "Brazil" else "o"
        size = 7.5 if region == "Brazil" else 5.0
        ax.plot(theta, stdn, marker=marker, color=REGION_COLORS.get(region, "0.4"),
                markeredgecolor="black", markeredgewidth=0.35, markersize=size,
                linestyle="None", label=region)


def plot_validation_figure(metrics: pd.DataFrame, taylor_df: pd.DataFrame, states: gpd.GeoDataFrame, out_dir: str):
    """Plot station-level climatological validation maps and Taylor diagrams.

    Station-level climatological metrics are mapped together with regional and national Taylor diagnostics.
    """
    fig = plt.figure(figsize=(25.0, 18.2), constrained_layout=False)
    gs = fig.add_gridspec(
        nrows=4,
        ncols=6,
        height_ratios=[1.0, 1.0, 1.0, 1.08],
        hspace=0.35,
        wspace=0.36,
        left=0.045,
        right=0.985,
        top=0.930,
        bottom=0.090,
    )

    metric_rows = [
        ("pearson_r", "Pearson\ncorrelation", plt.cm.RdYlBu_r, Normalize(vmin=-1, vmax=1), "Pearson r"),
        ("bias_era5_minus_inmet", "Bias\nERA5 − INMET", None, None, None),
        ("rmse", "RMSE", plt.cm.viridis, None, None),
    ]
    letters = list("abcdefghijklmnopqrstuvwxyz")
    letter_idx = 0

    for row_idx, (metric, row_title, cmap_base, norm_base, label_base) in enumerate(metric_rows):
        for col_idx, var in enumerate(VAR_ORDER):
            ax = fig.add_subplot(gs[row_idx, col_idx])
            d = metrics[metrics["variable"] == var].copy()
            meta = VARIABLES[var]

            if metric == "bias_era5_minus_inmet":
                cmap = plt.cm.RdBu_r
                norm = meta["bias_norm"]
                cbar_label = f"Bias ({meta['unit']})"
            elif metric == "rmse":
                cmap = plt.cm.viridis
                norm = meta["rmse_norm"]
                cbar_label = f"RMSE ({meta['unit']})"
            else:
                cmap = cmap_base
                norm = norm_base
                cbar_label = label_base

            format_map_axis(ax, states, row_idx=row_idx, col_idx=col_idx)
            sc = None
            if not d.empty:
                sc = ax.scatter(
                    d["lon"], d["lat"],
                    c=d[metric], cmap=cmap, norm=norm,
                    s=point_size_from_n(d["n_months"].values),
                    edgecolor="black", linewidth=0.18, alpha=0.92, zorder=5,
                )

            if row_idx == 0:
                ax.set_title(meta["label"], fontsize=13, fontweight="bold", pad=7)
            if col_idx == 0:
                ax.text(-0.19, 0.5, row_title, transform=ax.transAxes, rotation=90,
                        va="center", ha="center", fontsize=13.0, fontweight="bold")

            ax.text(0.018, 0.982, f"({letters[letter_idx]})", transform=ax.transAxes,
                    ha="left", va="top", fontsize=13,
                    bbox=dict(facecolor="white", edgecolor="none", alpha=0.78, pad=1.2),
                    zorder=10)
            letter_idx += 1

            if sc is not None:
                cb = fig.colorbar(sc, ax=ax, orientation="vertical", fraction=0.036, pad=0.010)
                cb.set_label(cbar_label, fontsize=12, labelpad=3)
                cb.ax.tick_params(labelsize=12, length=2.5, width=0.45)

    # Taylor diagrams row.
    for col_idx, var in enumerate(VAR_ORDER):
        ax = fig.add_subplot(gs[3, col_idx], projection="polar")
        setup_taylor_axis(ax, VARIABLES[var]["short_label"])
        plot_taylor_points(ax, taylor_df, var)
        if col_idx == 0:
            ax.text(-0.36, 0.5, "Taylor\ndiagrams", transform=ax.transAxes, rotation=90,
                    va="center", ha="center", fontsize=14.0, fontweight="bold")
        ax.text(-0.08, 1.08, f"({letters[letter_idx]})", transform=ax.transAxes,
                ha="left", va="top", fontsize=14,
                bbox=dict(facecolor="white", edgecolor="none", alpha=0.78, pad=1.2),
                zorder=10)
        letter_idx += 1

    # Compact legends are placed below the figure.
    nvals = metrics["n_months"].dropna().values
    if len(nvals) > 0:
        qvals = np.unique(np.nanpercentile(nvals, [25, 50, 75]).astype(int))
        handles = [plt.scatter([], [], s=point_size_from_n(np.array([q]))[0], facecolor="0.65",
                               edgecolor="black", linewidth=0.25, label=f"{q} months") for q in qvals]
        fig.legend(handles=handles, loc="lower left", bbox_to_anchor=(0.046, 0.020),
                   frameon=False, title="Station sample size", fontsize=12, title_fontsize=12)

    region_handles = [Line2D([0], [0], marker=("*" if r == "Brazil" else "o"), linestyle="None",
                             color=REGION_COLORS[r], markeredgecolor="black", markeredgewidth=0.35,
                             markersize=(8 if r == "Brazil" else 6.5), label=r)
                      for r in REGION_ORDER]
    obs_handle = Line2D([0], [0], marker="*", linestyle="None", color="black", markersize=8, label="INMET reference")
    fig.legend(region_handles + [obs_handle], [h.get_label() for h in region_handles] + ["INMET reference"],
               loc="lower center", ncol=7, frameon=False, bbox_to_anchor=(0.57, 0.020), fontsize=12)

    fig.suptitle(
        "ERA5 validation against INMET 1991–2020 climatological normals",
        x=0.055, y=0.982, ha="left", fontsize=18, fontweight="bold",
    )

    out_base = os.path.join(out_dir, "Supplementary_Figure_ERA5_INMET_climatological_normals_validation_1991_2020")
    fig.savefig(out_base + ".jpeg", dpi=500, bbox_inches="tight", facecolor="white")
    fig.savefig(out_base + ".pdf", dpi=500, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print(f"[OK] Saved: {out_base}.jpeg")
    print(f"[OK] Saved: {out_base}.pdf")


# ============================================================
# Main
# ============================================================

def main():
    ap = argparse.ArgumentParser(
        description=(
            "Validate ERA5 monthly climatology against INMET 1991–2020 "
            "climatological normals."
        )
    )
    ap.add_argument(
        "--normal-dir", "--normal_dir",
        dest="normal_dir",
        required=True,
        help="Directory containing INMET climatological-normal Excel files.",
    )
    ap.add_argument(
        "--era5-hourly-glob", "--era5_hourly_glob",
        dest="era5_hourly_glob",
        default=None,
        help=(
            "Glob pattern for hourly ERA5 NetCDF files. Required for hourly "
            "mode and as the fallback source in auto mode."
        ),
    )
    ap.add_argument(
        "--era5-daily-dir", "--era5_daily_dir",
        dest="era5_daily_dir",
        default=None,
        help=(
            "Directory containing preprocessed daily ERA5 files generated by "
            "the Figure 01 workflow."
        ),
    )
    ap.add_argument(
        "--source",
        choices=["auto", "daily", "hourly"],
        default="auto",
        help=(
            "ERA5 source mode. 'auto' uses daily files when available and "
            "otherwise falls back to hourly files."
        ),
    )
    ap.add_argument(
        "--states-shapefile", "--shp_uf",
        dest="shp_uf",
        required=True,
        help="Brazilian state shapefile.",
    )
    ap.add_argument(
        "--output-dir", "--out_dir",
        dest="out_dir",
        required=True,
        help="Output directory.",
    )
    ap.add_argument(
        "--daily-time-basis", "--daily_time_basis",
        dest="daily_time_basis",
        choices=["utc", "local_by_uf"],
        default="local_by_uf",
        help=(
            "Time basis used before daily aggregation in hourly mode. "
            "Default: local_by_uf."
        ),
    )
    ap.add_argument(
        "--reuse-era5-cache", "--reuse_era5_cache",
        dest="reuse_era5_cache",
        action="store_true",
        help="Reuse yearly and combined ERA5 station-month caches.",
    )
    ap.add_argument(
        "--max-years-per-run", "--max_years_per_run",
        dest="max_years_per_run",
        type=int,
        default=None,
        help="Process at most this many uncached ERA5 years in one run.",
    )
    ap.add_argument(
        "--build-era5-cache-only", "--build_era5_cache_only",
        dest="build_era5_cache_only",
        action="store_true",
        help="Build/reuse ERA5 caches without computing metrics or plotting.",
    )
    ap.add_argument(
        "--min-months", "--min_months",
        dest="min_months",
        type=int,
        default=8,
        help="Minimum paired months required for station-level metrics.",
    )
    args = ap.parse_args()

    if args.source == "daily" and not args.era5_daily_dir:
        ap.error("--era5-daily-dir is required when --source daily is used.")
    if args.source == "hourly" and not args.era5_hourly_glob:
        ap.error("--era5-hourly-glob is required when --source hourly is used.")
    if args.source == "auto" and not args.era5_daily_dir and not args.era5_hourly_glob:
        ap.error(
            "--source auto requires --era5-daily-dir and/or --era5-hourly-glob."
        )

    ensure_dir(args.out_dir)
    print("[START] ERA5 vs INMET climatological-normal validation, 1991-2020")
    print(f"[INFO] INMET normal directory: {args.normal_dir}")
    print(f"[INFO] ERA5 hourly glob: {args.era5_hourly_glob or 'not supplied'}")
    print(f"[INFO] ERA5 daily directory: {args.era5_daily_dir or 'not supplied'}")
    print(f"[INFO] ERA5 source mode: {args.source}")
    print(f"[INFO] Time basis for ERA5 aggregation: {args.daily_time_basis}")

    stations = read_station_metadata(args.normal_dir)
    inmet_normals = read_all_inmet_normals(args.normal_dir, stations)

    era5_clim, grid_index = build_era5_monthly_climatology(
        era5_glob=args.era5_hourly_glob,
        stations=stations,
        out_dir=args.out_dir,
        daily_time_basis=args.daily_time_basis,
        reuse_cache=args.reuse_era5_cache,
        max_years_per_run=args.max_years_per_run,
        build_cache_only=args.build_era5_cache_only,
        era5_daily_dir=args.era5_daily_dir,
        source=args.source,
    )

    if args.build_era5_cache_only:
        return

    paired = inmet_normals.merge(
        era5_clim,
        on=["station_id", "variable", "month"],
        how="inner",
    )
    paired = paired.dropna(subset=["inmet_normal", "era5_climatology", "lat", "lon"])
    paired["difference_era5_minus_inmet"] = paired["era5_climatology"] - paired["inmet_normal"]
    print(f"[INFO] Paired INMET-ERA5 station-month rows: {len(paired)}")

    station_metrics = station_metric_table(paired, min_months=args.min_months)
    print(f"[INFO] Station-level metrics rows: {len(station_metrics)}")
    taylor_df = compute_taylor_metrics(paired)
    states = read_states_shapefile(args.shp_uf)

    metadata = {
        "script": Path(__file__).name,
        "period": f"{START_YEAR}-{END_YEAR}",
        "normal_dir": args.normal_dir,
        "era5_hourly_glob": args.era5_hourly_glob,
        "era5_daily_dir": args.era5_daily_dir,
        "era5_source": args.source,
        "states_shapefile": args.shp_uf,
        "daily_time_basis": args.daily_time_basis,
        "daily_mode_note": (
            "Preprocessed daily files retain their existing calendar-day "
            "definition; state-level local-day shifting is applied only in "
            "hourly mode."
        ),
        "variables": VAR_ORDER,
        "units": {v: VARIABLES[v]["unit"] for v in VAR_ORDER},
        "era5_aggregation": {
            "TMAX": "daily maximum 2-m temperature, then monthly climatological mean",
            "TMIN": "daily minimum 2-m temperature, then monthly climatological mean",
            "TORV": "daily mean 2-m dew-point temperature, then monthly climatological mean",
            "UR": "daily mean relative humidity calculated from 2-m temperature and dew point, then monthly climatological mean",
            "VENTIN": "daily mean 10-m wind speed from u10/v10, then monthly climatological mean",
            "TMEDUMID": "daily mean wet-bulb temperature from Stull approximation, then monthly climatological mean",
        },
        "metrics": ["Pearson r", "RMSE", "Bias = ERA5 - INMET", "MAE", "Taylor metrics"],
    }

    save_outputs(paired, station_metrics, taylor_df, stations, grid_index, args.out_dir, metadata)
    plot_validation_figure(station_metrics, taylor_df, states, args.out_dir)
    print("[DONE] ERA5 climatological-normal validation completed.")


if __name__ == "__main__":
    warnings.filterwarnings("ignore", category=RuntimeWarning)
    main()

