#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Figure 02 — Preferential dry-hot heatwave amplification and land transformation.

This script reproduces the Figure 02 analysis using the unit-consistent
DHW–HHW comparison metric generated by ``figure_01_heatwave_trends.py``.

Cross-regime comparison
-----------------------
The analysis uses the Figure 01 field:

    DHW_minus_HHW_TmaxOnly_intensity_trend_decade

defined as the difference between DHW and HHW Tmax-only intensity trends.
Both components use the same accumulated positive standardised Tmax severity,
allowing direct comparison on a common scale.

The statistical-support component of the diagnostic hotspot criterion uses
the common-scale DHW fields:

    DHW_TmaxOnly_intensity_trend_decade > 0
    AND DHW_TmaxOnly_intensity_pvalue <= 0.05

The >4 hotspot magnitude cutoff is retained as the manuscript's diagnostic
cutoff for continuity. It is not interpreted as a universal physical threshold
and must be reassessed in the dedicated hotspot-threshold sensitivity analysis
using the common-scale contrast.

Panels
------
(a) DHW–HHW contrast map using the common-scale DHW–HHW contrast.
(b) Cumulative non-native-cover fraction in 2024 (=100 - native vegetation cover).
(c) Diagnostic strong-transition hotspots:
        DHW–HHW > 4 Tmax-standardized severity decade-1
        AND DHW Tmax-only trend > 0
        AND DHW Tmax-only p <= 0.05.
(d) Region-specific GAM/LOWESS associations:
        2024 non-native-cover fraction -> DHW–HHW contrast.
(e) Regional median and interquartile range of the transition.

Important methodological note
-----------------------------
``transformed_non_native_pct_2024`` is defined as ``100 - native vegetation cover``.

Inputs
------
--figure1-trends
    Figure 01 trend NetCDF containing the common-scale HHW/DHW fields.
--mapbiomas-xlsx
    MapBiomas Collection 10.1 municipality/state/biome coverage workbook.
--municipality-shapefile
    2024 Brazilian municipality shapefile.
--output-dir
    Output directory for Figure 02 and intermediate summary tables.

Outputs
-------
figure_02_land_transformation.jpeg
figure_02_land_transformation.pdf
figure_02_municipality_dhw_hhw_contrast_1990_2024.csv
figure_02_region_summary_dhw_hhw_contrast_1990_2024.csv
figure_02_regional_model_summary_dhw_hhw_contrast_1990_2024.csv

Usage
-----
python figure_02_land_transformation.py \
    --figure1-trends /path/to/figure_01_outputs/data/figure_01_heatwave_trends_1990_2024.nc \
    --mapbiomas-xlsx /path/to/mapbiomas_municipality_coverage.xlsx \
    --municipality-shapefile /path/to/brazil_municipalities_2024.shp \
    --output-dir ./outputs/figure_02

"""

import os
import re
import argparse
import warnings
import unicodedata
from pathlib import Path


import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
from scipy.spatial import cKDTree
from scipy import stats

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize, TwoSlopeNorm, ListedColormap, BoundaryNorm
from matplotlib.gridspec import GridSpec, GridSpecFromSubplotSpec
from mpl_toolkits.axes_grid1 import make_axes_locatable

import statsmodels.api as sm
from statsmodels.nonparametric.smoothers_lowess import lowess
from patsy import dmatrix


# ============================================================
# Runtime paths and period
# ============================================================

COVERAGE_XLSX = None
ERA5_TRENDS_NC = None
MUNICIPALITY_SHP = None
OUT_DIR = None

YEAR0 = 1990
YEAR1 = 2024


def parse_args():
    """Parse filesystem arguments; scientific/plotting settings remain fixed."""
    parser = argparse.ArgumentParser(
        description=(
            "Reproduce Figure 02 using the common-scale "
            "Tmax-standardized DHW-HHW contrast from Figure 01."
        )
    )
    parser.add_argument(
        "--figure1-trends",
        required=True,
        help="Figure 01 trend NetCDF.",
    )
    parser.add_argument(
        "--mapbiomas-xlsx",
        required=True,
        help="MapBiomas Collection 10.1 coverage workbook.",
    )
    parser.add_argument(
        "--municipality-shapefile",
        required=True,
        help="Brazilian municipality shapefile.",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Output directory for Figure 02 products.",
    )
    return parser.parse_args()


def configure_paths(args):
    """Populate runtime paths without embedding workstation/HPC-specific paths."""
    global COVERAGE_XLSX, ERA5_TRENDS_NC, MUNICIPALITY_SHP, OUT_DIR

    COVERAGE_XLSX = str(Path(args.mapbiomas_xlsx).expanduser().resolve())
    ERA5_TRENDS_NC = str(Path(args.figure1_trends).expanduser().resolve())
    MUNICIPALITY_SHP = str(Path(args.municipality_shapefile).expanduser().resolve())
    OUT_DIR = str(Path(args.output_dir).expanduser().resolve())

    for path, label in [
        (COVERAGE_XLSX, "MapBiomas workbook"),
        (ERA5_TRENDS_NC, "Figure 01 trends"),
        (MUNICIPALITY_SHP, "municipality shapefile"),
    ]:
        if not os.path.isfile(path):
            raise FileNotFoundError(f"{label} not found: {path}")

    os.makedirs(OUT_DIR, exist_ok=True)


# ============================================================
# Configuration
# ============================================================

MIN_AREA_HA = 1000.0

LON_MIN, LON_MAX = -75.5, -32.0
LAT_MIN, LAT_MAX = -35.5, 6.5

N_BOOT = 500
N_PERM = 999
RANDOM_SEED = 42

SPLINE_DF = 3
MIN_N_FOR_GAM = 60

DRY_SHIFT_THRESHOLD = 4.0
P_THRESHOLD = 0.05
MUNICIPAL_SIGPOS_FRACTION_THRESHOLD = 0.50

# Corrected, unit-consistent Figure 01 fields used by Figure 02.
DRY_SHIFT_SOURCE_VAR = "DHW_minus_HHW_TmaxOnly_intensity_trend_decade"
DHW_COMMON_TREND_VAR = "DHW_TmaxOnly_intensity_trend_decade"
HHW_COMMON_TREND_VAR = "HHW_TmaxOnly_intensity_trend_decade"
DHW_COMMON_PVALUE_VAR = "DHW_TmaxOnly_intensity_pvalue"

# Internal alias retained to preserve the plotting/dataframe structure.
DRY_SHIFT_ALIAS = "dry_minus_humid_intensity_trend"
DRY_SHIFT_UNITS = "Tmax-standardized severity decade$^{-1}$"

DRY_SHIFT_VMIN, DRY_SHIFT_VCENTER, DRY_SHIFT_VMAX = -1.5, 1.5, 6.5
AGRI_VMIN, AGRI_VMAX = 0.0, 35.0
TRANSFORMED_VMIN, TRANSFORMED_VMAX = 0.0, 100.0

REGION_ORDER = [
    "Amazônia",
    "Cerrado",
    "MATOPIBA",
    "Semiárido",
    "Sudeste urbano",
    "Pantanal",
    "Mata Atlântica",
    "Pampas",
]

GAM_REGIONS = ["Amazônia", "Cerrado", "MATOPIBA", "Sudeste urbano"]

MATOPIBA_STATES = {"MA", "TO", "PI", "BA"}
SEMIARID_STATES = {"AL", "BA", "CE", "PB", "PE", "PI", "RN", "SE", "MG"}
SOUTHEAST_STATES = {"SP", "RJ", "MG", "ES"}

NATIVE_LEVEL1 = {"1. forest", "2. non forest natural formation"}
AGRO_LEVEL1 = {"3. farming"}
URBAN_LEVEL2 = {"4.2. urban area"}

CMAP_DRYSHIFT = plt.cm.RdBu_r
CMAP_AGRI = plt.cm.YlOrBr
CMAP_HOTSPOT = ListedColormap(["#F2F2F2", "#B2182B"])
NORM_HOTSPOT = BoundaryNorm([-0.5, 0.5, 1.5], CMAP_HOTSPOT.N)


# ============================================================
# NetCDF backend helper
# ============================================================

def _available_netcdf_engines():
    engines = xr.backends.list_engines()
    return [name for name in ("h5netcdf", "netcdf4", "scipy") if name in engines]


def safe_open_dataset(path, *, decode_times=True, chunks=None, **kwargs):
    """Open NetCDF with explicit backend fallback."""
    errors = []
    for engine in _available_netcdf_engines():
        try:
            return xr.open_dataset(
                path,
                engine=engine,
                decode_times=decode_times,
                chunks=chunks,
                **kwargs,
            )
        except Exception as exc:
            errors.append(f"{engine}: {type(exc).__name__}: {exc}")

    raise RuntimeError(
        f"Could not open NetCDF file: {path}\n" + "\n".join(errors)
    )


# ============================================================
# Helpers
# ============================================================

def normalize_text(x):
    if pd.isna(x):
        return ""
    s = str(x).strip()
    s = unicodedata.normalize("NFKD", s)
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = s.upper()
    s = re.sub(r"\s+", " ", s)
    return s


def normalize_class(x):
    if pd.isna(x):
        return ""
    s = str(x).strip().lower()
    s = unicodedata.normalize("NFKD", s)
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = re.sub(r"\s+", " ", s)
    return s


def normalize_biome(x):
    s = normalize_text(x)
    mapping = {
        "AMAZONIA": "Amazônia",
        "CERRADO": "Cerrado",
        "CAATINGA": "Caatinga",
        "MATA ATLANTICA": "Mata Atlântica",
        "PAMPA": "Pampas",
        "PAMPAS": "Pampas",
        "PANTANAL": "Pantanal",
    }
    return mapping.get(s, str(x))


def detect_column(columns, candidates):
    norm_map = {normalize_text(c): c for c in columns}
    for cand in candidates:
        nc = normalize_text(cand)
        if nc in norm_map:
            return norm_map[nc]
    for col in columns:
        nc = normalize_text(col)
        for cand in candidates:
            if normalize_text(cand) in nc:
                return col
    return None


def find_municipality_shapefile():
    """Return the validated runtime municipality shapefile."""
    if MUNICIPALITY_SHP and os.path.isfile(MUNICIPALITY_SHP):
        return MUNICIPALITY_SHP
    raise FileNotFoundError(f"Municipality shapefile not found: {MUNICIPALITY_SHP}")


def safe_div(num, den):
    num = np.asarray(num, dtype=float)
    den = np.asarray(den, dtype=float)
    return np.where((den > 0) & np.isfinite(den), num / den, np.nan)


def weighted_mean_values(values, weights):
    values = np.asarray(values, dtype=float)
    weights = np.asarray(weights, dtype=float)
    ok = np.isfinite(values) & np.isfinite(weights) & (weights > 0)
    if not np.any(ok):
        return np.nan
    return float(np.average(values[ok], weights=weights[ok]))


def weighted_mean(g, value_col, weight_col="total_area_2024_ha"):
    return weighted_mean_values(
        pd.to_numeric(g[value_col], errors="coerce").values,
        pd.to_numeric(g[weight_col], errors="coerce").values
    )


def weighted_quantile(values, weights, q):
    values = np.asarray(values, dtype=float)
    weights = np.asarray(weights, dtype=float)
    ok = np.isfinite(values) & np.isfinite(weights) & (weights > 0)
    if not np.any(ok):
        return np.nan
    values = values[ok]
    weights = weights[ok]
    order = np.argsort(values)
    values = values[order]
    weights = weights[order]
    cdf = np.cumsum(weights) / np.sum(weights)
    return float(values[np.searchsorted(cdf, q)])


def _weighted_pearson_core(x, y, w):
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    w = np.asarray(w, dtype=float)
    ok = np.isfinite(x) & np.isfinite(y) & np.isfinite(w) & (w > 0)
    if ok.sum() < 3:
        return np.nan
    x, y, w = x[ok], y[ok], w[ok]
    mx = np.average(x, weights=w)
    my = np.average(y, weights=w)
    cov = np.average((x - mx) * (y - my), weights=w)
    vx = np.average((x - mx) ** 2, weights=w)
    vy = np.average((y - my) ** 2, weights=w)
    if vx <= 0 or vy <= 0:
        return np.nan
    return float(cov / np.sqrt(vx * vy))


def weighted_spearman(x, y, w, n_perm=N_PERM, seed=RANDOM_SEED):
    """Area-weighted Spearman rho with a two-sided permutation p-value."""
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    w = np.asarray(w, dtype=float)
    ok = np.isfinite(x) & np.isfinite(y) & np.isfinite(w) & (w > 0)
    if ok.sum() < 10:
        return np.nan, np.nan
    x, y, w = x[ok], y[ok], w[ok]
    xr = stats.rankdata(x)
    yr = stats.rankdata(y)
    rho = _weighted_pearson_core(xr, yr, w)
    if not np.isfinite(rho):
        return np.nan, np.nan
    rng = np.random.default_rng(seed)
    exceed = 0
    for _ in range(int(n_perm)):
        rp = _weighted_pearson_core(xr, rng.permutation(yr), w)
        if np.isfinite(rp) and abs(rp) >= abs(rho):
            exceed += 1
    p = (exceed + 1.0) / (int(n_perm) + 1.0)
    return float(rho), float(p)


# ============================================================
# MapBiomas processing
# ============================================================

def read_mapbiomas():
    print(f"[INFO] Reading MapBiomas coverage: {COVERAGE_XLSX}")
    df = pd.read_excel(COVERAGE_XLSX, sheet_name="COVERAGE_10.1")

    required = [
        "country", "biome", "state", "state_acronym", "municipality",
        "class_level_1", "class_level_2", YEAR0, YEAR1
    ]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Missing columns in MapBiomas file: {missing}")

    for y in [YEAR0, YEAR1]:
        df[y] = pd.to_numeric(df[y], errors="coerce")

    df["municipality_norm"] = df["municipality"].map(normalize_text)
    df["state_acronym_norm"] = df["state_acronym"].map(normalize_text)
    df["biome_clean"] = df["biome"].map(normalize_biome)
    df["class1_norm"] = df["class_level_1"].map(normalize_class)
    df["class2_norm"] = df["class_level_2"].map(normalize_class)

    return df


def build_landcover_municipality_biome(df):
    print(f"[INFO] Building land-cover metrics for {YEAR0}–{YEAR1}.")

    id_cols = [
        "country", "biome", "biome_clean", "state", "state_acronym",
        "municipality", "municipality_norm", "state_acronym_norm"
    ]

    total = (
        df.groupby(id_cols, dropna=False)[[YEAR0, YEAR1]]
        .sum()
        .rename(columns={YEAR0: "total_area_1990_ha", YEAR1: "total_area_2024_ha"})
        .reset_index()
    )

    def agg(mask, prefix):
        return (
            df.loc[mask]
            .groupby(id_cols, dropna=False)[[YEAR0, YEAR1]]
            .sum()
            .rename(columns={YEAR0: f"{prefix}_1990_ha", YEAR1: f"{prefix}_2024_ha"})
            .reset_index()
        )

    out = total.copy()
    groups = {
        "native": df["class1_norm"].isin(NATIVE_LEVEL1),
        "agro": df["class1_norm"].isin(AGRO_LEVEL1),
        "urban": df["class2_norm"].isin(URBAN_LEVEL2),
    }

    for prefix, mask in groups.items():
        out = out.merge(agg(mask, prefix), on=id_cols, how="left")

    area_cols = [c for c in out.columns if c.endswith("_ha")]
    out[area_cols] = out[area_cols].fillna(0.0)

    before = len(out)
    out = out[out["total_area_2024_ha"] >= MIN_AREA_HA].copy()
    print(f"[QC] Removed {before - len(out)} municipality-biome rows with area < {MIN_AREA_HA:.0f} ha.")

    den0 = out["total_area_1990_ha"].values
    den1 = out["total_area_2024_ha"].values

    for group in ["native", "agro", "urban"]:
        out[f"{group}_frac_1990"] = safe_div(out[f"{group}_1990_ha"].values, den0)
        out[f"{group}_frac_2024"] = safe_div(out[f"{group}_2024_ha"].values, den1)
        out[f"{group}_pct_1990"] = 100.0 * out[f"{group}_frac_1990"]
        out[f"{group}_pct_2024"] = 100.0 * out[f"{group}_frac_2024"]

    out["veg_loss_pct_points"] = out["native_pct_1990"] - out["native_pct_2024"]
    out["agri_gain_pct_points"] = out["agro_pct_2024"] - out["agro_pct_1990"]
    out["urban_gain_pct_points"] = out["urban_pct_2024"] - out["urban_pct_1990"]

    return out


# ============================================================
# Geometry and ERA5 zonal integration
# ============================================================

def load_municipality_geometry():
    shp = find_municipality_shapefile()
    print(f"[INFO] Reading municipality shapefile: {shp}")

    gdf = gpd.read_file(shp).to_crs(epsg=4326)

    name_col = detect_column(gdf.columns, [
        "NM_MUN", "NM_MUNICIP", "NM_MUNICIPIO", "NOME", "MUNICIPIO", "municipality", "name"
    ])
    state_col = detect_column(gdf.columns, [
        "SIGLA_UF", "UF", "state_acronym", "SIGLA"
    ])

    if name_col is None or state_col is None:
        raise ValueError(f"Could not detect municipality/state columns. Columns: {list(gdf.columns)}")

    gdf["municipality_norm"] = gdf[name_col].map(normalize_text)
    gdf["state_acronym_norm"] = gdf[state_col].map(normalize_text)

    pts = gdf.geometry.representative_point()
    gdf["rep_lon"] = pts.x
    gdf["rep_lat"] = pts.y

    return gdf


def aggregate_to_municipality(df):
    print("[INFO] Aggregating municipality-biome rows to municipality level.")

    rows = []
    group_cols = ["municipality_norm", "state_acronym_norm"]

    vars_to_weight = [
        "veg_loss_pct_points",
        "agri_gain_pct_points",
        "urban_gain_pct_points",
        "native_pct_1990",
        "native_pct_2024",
        "agro_pct_1990",
        "agro_pct_2024",
        "urban_pct_1990",
        "urban_pct_2024",
    ]

    for keys, g in df.groupby(group_cols, dropna=False):
        municipality_norm, state_acronym_norm = keys
        total_area = g["total_area_2024_ha"].sum()

        row = {
            "municipality_norm": municipality_norm,
            "state_acronym_norm": state_acronym_norm,
            "municipality": g["municipality"].iloc[0],
            "state_acronym": g["state_acronym"].iloc[0],
            "total_area_2024_ha": total_area,
            "n_biome_rows": len(g),
        }

        gi = g.loc[g["total_area_2024_ha"].idxmax()]
        row["dominant_biome"] = gi["biome_clean"]
        row["dominant_biome_area_fraction"] = (
            gi["total_area_2024_ha"] / total_area if total_area > 0 else np.nan
        )

        for c in vars_to_weight:
            row[c] = weighted_mean(g, c)

        rows.append(row)

    out = pd.DataFrame(rows)

    # Cumulative landscape-state metrics used in the revised main Figure 2.
    # These variables capture the 2024 transformed state of each municipality,
    # which the controlled diagnostics showed to be more robust than recent
    # agricultural expansion alone.
    out["transformed_non_native_pct_2024"] = 100.0 - pd.to_numeric(out["native_pct_2024"], errors="coerce")
    out["transformed_non_native_pct_1990"] = 100.0 - pd.to_numeric(out["native_pct_1990"], errors="coerce")

    out = add_focus_regions(out)
    return out


def add_focus_regions(df):
    df = df.copy()

    state = df["state_acronym_norm"].astype(str).str.upper()
    dom = df["dominant_biome"].astype(str)

    se = state.isin(SOUTHEAST_STATES)
    urban_gain = pd.to_numeric(df["urban_gain_pct_points"], errors="coerce")
    urban_pct_2024 = pd.to_numeric(df.get("urban_pct_2024", np.nan), errors="coerce")

    se_gain_thr = np.nanpercentile(urban_gain[se], 75) if np.isfinite(urban_gain[se]).any() else np.nan
    se_urban_thr = np.nanpercentile(urban_pct_2024[se], 75) if np.isfinite(urban_pct_2024[se]).any() else np.nan

    is_southeast_urban = se & ((urban_gain >= se_gain_thr) | (urban_pct_2024 >= se_urban_thr))
    is_matopiba = state.isin(MATOPIBA_STATES) & dom.isin(["Cerrado", "Caatinga"])
    is_semiarid = state.isin(SEMIARID_STATES) & dom.eq("Caatinga")

    region = dom.copy().astype(object)
    region[is_semiarid.values] = "Semiárido"
    region[is_matopiba.values] = "MATOPIBA"
    region[is_southeast_urban.values] = "Sudeste urbano"

    region = np.where(np.isin(region, REGION_ORDER), region, "Other")
    df["focus_region"] = region

    return df


def build_era5_point_gdf(ds):
    lon = ds["lon"].values
    lat = ds["lat"].values

    if np.nanmax(lon) > 180:
        lon = ((lon + 180) % 360) - 180

    lon2d, lat2d = np.meshgrid(lon, lat)

    data = {
        "era5_lat": lat2d.ravel(),
        "era5_lon": lon2d.ravel(),
    }

    trend_vars = [v for v in ds.data_vars if v.endswith("_trend_decade") or v.endswith("_pvalue")]

    for v in trend_vars:
        arr = ds[v].values
        data[v] = arr.ravel()

    pts = gpd.GeoDataFrame(
        data,
        geometry=gpd.points_from_xy(data["era5_lon"], data["era5_lat"]),
        crs="EPSG:4326"
    )

    pts = pts[
        (pts["era5_lon"] >= LON_MIN - 1)
        & (pts["era5_lon"] <= LON_MAX + 1)
        & (pts["era5_lat"] >= LAT_MIN - 1)
        & (pts["era5_lat"] <= LAT_MAX + 1)
    ].copy()

    return pts, trend_vars


def aggregate_era5_to_municipalities_zonal(gdf_mun, ds):
    """Aggregate continuous ERA5 trends with cos(latitude) weights.

    P-values are not averaged. Municipality statistical support is represented
    by the cos(latitude)-weighted fraction of contributing grid cells with a
    positive DHW Tmax-only trend and p <= 0.05.
    """
    print("[INFO] Integrating ERA5 trends by municipality zonal aggregation.")
    pts, vars_all = build_era5_point_gdf(ds)
    pts["grid_weight"] = np.cos(np.deg2rad(pd.to_numeric(pts["era5_lat"], errors="coerce")))
    pts.loc[~np.isfinite(pts["grid_weight"]) | (pts["grid_weight"] <= 0), "grid_weight"] = np.nan

    keys = ["municipality_norm", "state_acronym_norm"]
    gdf_small = gdf_mun[keys + ["rep_lon", "rep_lat", "geometry"]].copy()

    try:
        joined = gpd.sjoin(
            pts,
            gdf_small[keys + ["geometry"]],
            how="inner",
            predicate="within",
        )
    except Exception as exc:
        print(f"[WARN] Spatial join failed: {exc}")
        print("[WARN] Falling back to nearest-grid extraction.")
        return aggregate_era5_to_municipalities_nearest(gdf_mun, ds)

    trend_vars = [v for v in vars_all if v.endswith("_trend_decade")]
    rows = []

    for name, g in joined.groupby(keys, dropna=False):
        w = pd.to_numeric(g["grid_weight"], errors="coerce").to_numpy(float)
        row = {
            "municipality_norm": name[0],
            "state_acronym_norm": name[1],
            "era5_integration_method": "zonal_gridpoint_coslat_weighted",
            "era5_n_gridpoints": int(len(g)),
            "era5_mean_lat": weighted_mean_values(g["era5_lat"], w),
            "era5_mean_lon": weighted_mean_values(g["era5_lon"], w),
        }

        for var in trend_vars:
            row[var] = weighted_mean_values(
                pd.to_numeric(g[var], errors="coerce").to_numpy(float),
                w,
            )

        tr = pd.to_numeric(g[DHW_COMMON_TREND_VAR], errors="coerce").to_numpy(float)
        pv = pd.to_numeric(g[DHW_COMMON_PVALUE_VAR], errors="coerce").to_numpy(float)
        valid = np.isfinite(tr) & np.isfinite(pv) & np.isfinite(w) & (w > 0)
        sigpos = valid & (tr > 0) & (pv <= P_THRESHOLD)
        row["DHW_TmaxOnly_significant_positive_fraction"] = (
            float(np.sum(w[sigpos]) / np.sum(w[valid]))
            if np.any(valid) else np.nan
        )
        rows.append(row)

    zonal = pd.DataFrame(rows)

    missing = (
        gdf_small[keys + ["rep_lon", "rep_lat"]]
        .merge(zonal[keys], on=keys, how="left", indicator=True)
        .query("_merge == 'left_only'")
        .drop(columns="_merge")
    )

    print(f"[INFO] Zonal ERA5 matched municipalities: {len(zonal)}")
    print(f"[INFO] Nearest-grid fallback municipalities: {len(missing)}")

    if len(missing) > 0:
        nearest = aggregate_era5_to_municipalities_nearest(
            gdf_small.merge(missing[keys], on=keys, how="inner"),
            ds,
        )
        return pd.concat([zonal, nearest], ignore_index=True)

    return zonal


def aggregate_era5_to_municipalities_nearest(gdf_mun, ds):
    lon = ds["lon"].values
    lat = ds["lat"].values

    if np.nanmax(lon) > 180:
        lon = ((lon + 180) % 360) - 180

    lon2d, lat2d = np.meshgrid(lon, lat)
    points = np.column_stack([lat2d.ravel(), lon2d.ravel()])
    tree = cKDTree(points)

    keys = ["municipality_norm", "state_acronym_norm"]

    out = gdf_mun[keys + ["rep_lon", "rep_lat"]].drop_duplicates().copy()
    ok = out["rep_lon"].notna() & out["rep_lat"].notna()

    query = np.column_stack([out.loc[ok, "rep_lat"].values, out.loc[ok, "rep_lon"].values])
    dist, idx = tree.query(query)

    out["era5_integration_method"] = "nearest_gridpoint_fallback"
    out["era5_n_gridpoints"] = 1
    out["era5_mean_lat"] = np.nan
    out["era5_mean_lon"] = np.nan
    out.loc[ok, "era5_mean_lat"] = points[idx, 0]
    out.loc[ok, "era5_mean_lon"] = points[idx, 1]
    out["era5_nearest_distance_deg"] = np.nan
    out.loc[ok, "era5_nearest_distance_deg"] = dist

    vars_all = [v for v in ds.data_vars if v.endswith("_trend_decade") or v.endswith("_pvalue")]

    for v in vars_all:
        arr = ds[v].values
        vals = np.full(len(out), np.nan)

        if ok.any():
            lat_idx = np.array([np.argmin(np.abs(lat - la)) for la in out.loc[ok, "era5_mean_lat"].values])
            lon_idx = np.array([np.argmin(np.abs(lon - lo)) for lo in out.loc[ok, "era5_mean_lon"].values])
            vals[ok.values] = arr[lat_idx, lon_idx]

        out[v] = vals

    tr = pd.to_numeric(out[DHW_COMMON_TREND_VAR], errors="coerce")
    pv = pd.to_numeric(out[DHW_COMMON_PVALUE_VAR], errors="coerce")
    valid = tr.notna() & pv.notna()
    out["DHW_TmaxOnly_significant_positive_fraction"] = np.where(
        valid,
        ((tr > 0) & (pv <= P_THRESHOLD)).astype(float),
        np.nan,
    )
    return out


def extract_era5_trends(mun_table, gdf):
    """
    Integrate Figure 01 fields to municipalities.

    The DHW–HHW contrast is read directly from the common-scale Figure 01
    contrast. Primary DHW and HHW regime-specific intensity fields are never
    subtracted in this workflow.
    """
    if not os.path.exists(ERA5_TRENDS_NC):
        raise FileNotFoundError(f"ERA5 trends file not found: {ERA5_TRENDS_NC}")

    print(f"[INFO] Reading Figure 01 trends: {ERA5_TRENDS_NC}")
    ds = safe_open_dataset(ERA5_TRENDS_NC, decode_times=False, chunks=None)

    required_source = [
        DRY_SHIFT_SOURCE_VAR,
        DHW_COMMON_TREND_VAR,
        HHW_COMMON_TREND_VAR,
        DHW_COMMON_PVALUE_VAR,
        "DHW_frequency_trend_decade",
        "DHW_duration_trend_decade",
    ]
    missing = [var for var in required_source if var not in ds.data_vars]
    if missing:
        ds.close()
        raise RuntimeError(
            "The supplied Figure 01 trend file is not compatible with "
            "Figure 02. Missing variables: " + ", ".join(missing)
        )

    era5_mun = aggregate_era5_to_municipalities_zonal(gdf, ds)

    out = mun_table.merge(
        era5_mun,
        on=["municipality_norm", "state_acronym_norm"],
        how="left",
    )

    # Preserve the historical dataframe/plotting alias, but source it directly
    # from the common-scale Figure 01 contrast.
    out[DRY_SHIFT_ALIAS] = pd.to_numeric(
        out[DRY_SHIFT_SOURCE_VAR],
        errors="coerce",
    )

    # Municipality hotspot criterion aligned with the Figure 1.
    # P-values are never averaged. Statistical support is the weighted fraction
    # of contributing ERA5 cells with positive significant DHW Tmax-only trends.
    dhw_common_trend = pd.to_numeric(out[DHW_COMMON_TREND_VAR], errors="coerce")
    sigpos_fraction = pd.to_numeric(
        out["DHW_TmaxOnly_significant_positive_fraction"],
        errors="coerce",
    )

    out["dry_hot_hotspot"] = (
        (out[DRY_SHIFT_ALIAS] > DRY_SHIFT_THRESHOLD)
        & (dhw_common_trend > 0)
        & (sigpos_fraction >= MUNICIPAL_SIGPOS_FRACTION_THRESHOLD)
    ).astype(int)

    out["dry_hot_hotspot_intensity"] = np.where(
        out["dry_hot_hotspot"] == 1,
        out[DRY_SHIFT_ALIAS],
        np.nan,
    )
    out["dry_shift_stipple"] = out["dry_hot_hotspot"].astype(bool)

    out_file = os.path.join(
        OUT_DIR,
        "figure_02_municipality_dhw_hhw_contrast_1990_2024.csv",
    )
    out.to_csv(out_file, index=False)

    print(f"[OK] Saved municipality table: {out_file}")
    print(
        "[INFO] Diagnostic hotspot criterion: DHW-HHW > "
        f"{DRY_SHIFT_THRESHOLD:.1f} {DRY_SHIFT_UNITS.replace('$', '')}; "
        f"DHW Tmax-only trend > 0; p <= {P_THRESHOLD:.2f}"
    )
    print(
        "[INFO] The >4 cutoff is retained as a diagnostic threshold for "
        "continuity and must be re-evaluated with the hotspot "
        "sensitivity workflow."
    )
    print(
        f"[INFO] Hotspot municipalities: "
        f"{int(out['dry_hot_hotspot'].sum())}/{len(out)}"
    )

    ds.close()
    return out

def merge_geometry(mun_table, gdf):
    merged = gdf.merge(
        mun_table,
        on=["municipality_norm", "state_acronym_norm"],
        how="left"
    )
    print(f"[INFO] Matched municipalities: {merged['focus_region'].notna().sum()}/{len(merged)}")
    return merged


# ============================================================
# Summary and GAM
# ============================================================

def build_region_summary(mun_table):
    print("[INFO] Building regional summary with median and IQR.")

    variables = [
        "veg_loss_pct_points",
        "agri_gain_pct_points",
        "urban_gain_pct_points",
        "agro_pct_2024",
        "native_pct_2024",
        "transformed_non_native_pct_2024",
        "DHW_TmaxOnly_intensity_trend_decade",
        "HHW_TmaxOnly_intensity_trend_decade",
        "dry_minus_humid_intensity_trend",
        "DHW_frequency_trend_decade",
        "DHW_duration_trend_decade",
        "dry_hot_hotspot",
    ]

    rows = []

    for region in REGION_ORDER:
        g = mun_table[mun_table["focus_region"] == region].copy()
        if g.empty:
            continue

        row = {
            "region": region,
            "n_municipalities": len(g),
            "area_2024_ha": g["total_area_2024_ha"].sum(),
        }

        weights = g["total_area_2024_ha"].values

        for v in variables:
            vals = pd.to_numeric(g[v], errors="coerce").values
            row[f"{v}_median"] = weighted_quantile(vals, weights, 0.50)
            row[f"{v}_p25"] = weighted_quantile(vals, weights, 0.25)
            row[f"{v}_p75"] = weighted_quantile(vals, weights, 0.75)
            row[f"{v}_mean"] = weighted_mean_values(vals, weights)

        rows.append(row)

    out = pd.DataFrame(rows)

    out_file = os.path.join(OUT_DIR, "figure_02_region_summary_dhw_hhw_contrast_1990_2024.csv")
    out.to_csv(out_file, index=False)
    print(f"[OK] Saved region summary: {out_file}")

    return out


def prepare_gam_data(mun_table, x_col, y_col, region=None):
    cols = [x_col, y_col, "focus_region", "total_area_2024_ha"]
    df = mun_table[cols].copy()

    if region is not None:
        df = df[df["focus_region"] == region].copy()
    else:
        df = df[df["focus_region"].isin(REGION_ORDER)].copy()

    df[x_col] = pd.to_numeric(df[x_col], errors="coerce")
    df[y_col] = pd.to_numeric(df[y_col], errors="coerce")
    df["total_area_2024_ha"] = pd.to_numeric(df["total_area_2024_ha"], errors="coerce")

    df = df.dropna(subset=[x_col, y_col, "focus_region", "total_area_2024_ha"])
    df = df[df["total_area_2024_ha"] > 0].copy()

    if len(df) < 10:
        return df

    # Fit domain is restricted to the 1st–99th percentile range.
    q01, q99 = np.nanpercentile(df[x_col], [1, 99])
    df = df[(df[x_col] >= q01) & (df[x_col] <= q99)].copy()

    w = np.sqrt(df["total_area_2024_ha"].values)
    df["gam_weight"] = w / np.nanmean(w)

    return df


def build_design_matrix(df, x_col, design_info=None):
    data = df[[x_col]].copy()
    data = data.rename(columns={x_col: "x"})

    formula = f"bs(x, df={SPLINE_DF}, degree=3, include_intercept=False)"

    if design_info is None:
        X = dmatrix(formula, data=data, return_type="dataframe")
        return X, X.design_info

    X = dmatrix(design_info, data=data, return_type="dataframe")
    return X, design_info


def fit_spline_model(df_fit, x_col, y_col):
    if len(df_fit) < MIN_N_FOR_GAM:
        return None

    unique_x = np.unique(np.round(df_fit[x_col].values, 6))
    if len(unique_x) <= SPLINE_DF + 2:
        X = sm.add_constant(df_fit[[x_col]])
        y = df_fit[y_col].values
        w = df_fit["gam_weight"].values
        fit = sm.WLS(y, X, weights=w).fit(cov_type="HC3")
        return {
            "fit": fit,
            "design_info": None,
            "x_col": x_col,
            "y_col": y_col,
            "linear": True,
        }

    X, design_info = build_design_matrix(df_fit, x_col)
    y = df_fit[y_col].values
    w = df_fit["gam_weight"].values

    model = sm.WLS(y, X, weights=w)
    fit = model.fit(cov_type="HC3")

    return {
        "fit": fit,
        "design_info": design_info,
        "x_col": x_col,
        "y_col": y_col,
        "linear": False,
    }


def predict_curve(model_info, x_grid):
    fit = model_info["fit"]
    x_col = model_info["x_col"]

    pred_df = pd.DataFrame({x_col: x_grid})

    if model_info.get("linear", False):
        Xp = sm.add_constant(pred_df[[x_col]], has_constant="add")
        return np.asarray(fit.predict(Xp), dtype=float)

    Xp, _ = build_design_matrix(pred_df, x_col, model_info["design_info"])
    return np.asarray(fit.predict(Xp), dtype=float)


def bootstrap_spline_curve(df_fit, x_col, y_col, x_grid):
    base = fit_spline_model(df_fit, x_col, y_col)
    if base is None:
        return None

    yhat = predict_curve(base, x_grid)

    rng = np.random.default_rng(RANDOM_SEED)
    boot = []

    for _ in range(N_BOOT):
        idx = rng.integers(0, len(df_fit), size=len(df_fit))
        db = df_fit.iloc[idx].copy()

        try:
            model_b = fit_spline_model(db, x_col, y_col)
            if model_b is None:
                continue
            yb = predict_curve(model_b, x_grid)
            if np.all(np.isfinite(yb)):
                boot.append(yb)
        except Exception:
            continue

    if len(boot) >= 20:
        boot = np.vstack(boot)
        lo = np.nanpercentile(boot, 2.5, axis=0)
        hi = np.nanpercentile(boot, 97.5, axis=0)
    else:
        lo = np.full_like(yhat, np.nan)
        hi = np.full_like(yhat, np.nan)

    rho, p = weighted_spearman(
        df_fit[x_col].values,
        df_fit[y_col].values,
        df_fit["gam_weight"].values,
    )

    q25 = np.nanpercentile(df_fit[x_col], 25)
    q75 = np.nanpercentile(df_fit[x_col], 75)

    low = df_fit[df_fit[x_col] <= q25][y_col].dropna()
    high = df_fit[df_fit[x_col] >= q75][y_col].dropna()

    delta = float(np.nanmedian(high) - np.nanmedian(low)) if len(low) >= 10 and len(high) >= 10 else np.nan

    return {
        "x": x_grid,
        "yhat": yhat,
        "lo": lo,
        "hi": hi,
        "n": len(df_fit),
        "rho": rho,
        "p": p,
        "delta_q4_q1": delta,
        "x_obs": df_fit[x_col].values,
    }


def bootstrap_lowess_curve(df_fit, x_col, y_col, x_grid, frac=0.70):
    """
    LOWESS smoother for heterogeneous urban signal.
    Used for Sudeste urbano to avoid unstable spline edge behaviour.
    LOWESS in statsmodels is unweighted; area weights are retained for summary
    diagnostics, but the smoother is intentionally descriptive.
    """
    if len(df_fit) < MIN_N_FOR_GAM:
        return None

    x = np.asarray(df_fit[x_col].values, dtype=float)
    y = np.asarray(df_fit[y_col].values, dtype=float)

    ok = np.isfinite(x) & np.isfinite(y)
    x = x[ok]
    y = y[ok]

    if len(x) < MIN_N_FOR_GAM:
        return None

    order = np.argsort(x)
    x_sorted = x[order]
    y_sorted = y[order]

    fit = lowess(y_sorted, x_sorted, frac=frac, it=1, return_sorted=True)
    # Remove duplicate x values before interpolation.
    xu, idx = np.unique(fit[:, 0], return_index=True)
    yu = fit[:, 1][idx]
    yhat = np.interp(x_grid, xu, yu)

    rng = np.random.default_rng(RANDOM_SEED)
    boot = []

    for _ in range(N_BOOT):
        idxb = rng.integers(0, len(x), size=len(x))
        xb = x[idxb]
        yb = y[idxb]
        try:
            order_b = np.argsort(xb)
            fb = lowess(yb[order_b], xb[order_b], frac=frac, it=1, return_sorted=True)
            xbu, ib = np.unique(fb[:, 0], return_index=True)
            ybu = fb[:, 1][ib]
            if len(xbu) >= 3:
                boot.append(np.interp(x_grid, xbu, ybu))
        except Exception:
            continue

    if len(boot) >= 20:
        boot = np.vstack(boot)
        lo = np.nanpercentile(boot, 2.5, axis=0)
        hi = np.nanpercentile(boot, 97.5, axis=0)
    else:
        lo = np.full_like(yhat, np.nan)
        hi = np.full_like(yhat, np.nan)

    rho, p = weighted_spearman(
        df_fit[x_col].values,
        df_fit[y_col].values,
        df_fit["gam_weight"].values,
    )

    q25 = np.nanpercentile(df_fit[x_col], 25)
    q75 = np.nanpercentile(df_fit[x_col], 75)
    low_q = df_fit[df_fit[x_col] <= q25][y_col].dropna()
    high_q = df_fit[df_fit[x_col] >= q75][y_col].dropna()
    delta = float(np.nanmedian(high_q) - np.nanmedian(low_q)) if len(low_q) >= 10 and len(high_q) >= 10 else np.nan

    return {
        "x": x_grid,
        "yhat": yhat,
        "lo": lo,
        "hi": hi,
        "n": len(df_fit),
        "rho": rho,
        "p": p,
        "delta_q4_q1": delta,
        "x_obs": df_fit[x_col].values,
        "method": "LOWESS",
    }


def run_regional_gam_models(mun_table):
    results = {}

    for region in GAM_REGIONS:
        df_fit = prepare_gam_data(
            mun_table,
            "transformed_non_native_pct_2024",
            "dry_minus_humid_intensity_trend",
            region=region
        )

        if len(df_fit) < MIN_N_FOR_GAM:
            print(f"[WARN] Insufficient data for regional GAM {region}: N={len(df_fit)}")
            results[region] = None
            continue

        # Use 1st–99th percentile for prediction domain.
        x = df_fit["transformed_non_native_pct_2024"].values
        q01, q99 = np.nanpercentile(x, [1, 99])
        x_grid = np.linspace(q01, q99, 300)

        if region == "Sudeste urbano":
            print(f"[INFO] Fitting regional LOWESS: {region}, N={len(df_fit)}")
            results[region] = bootstrap_lowess_curve(
                df_fit,
                "transformed_non_native_pct_2024",
                "dry_minus_humid_intensity_trend",
                x_grid,
                frac=0.70,
            )
        else:
            print(f"[INFO] Fitting regional GAM-like spline: {region}, N={len(df_fit)}, df={SPLINE_DF}")
            results[region] = bootstrap_spline_curve(
                df_fit,
                "transformed_non_native_pct_2024",
                "dry_minus_humid_intensity_trend",
                x_grid
            )
            if results[region] is not None:
                results[region]["method"] = "GAM spline"

    rows = []
    for region, res in results.items():
        if res is None:
            continue
        rows.append({
            "region": region,
            "n": res["n"],
            "weighted_spearman_rho": res["rho"],
            "weighted_spearman_p_permutation": res["p"],
            "delta_Q4_minus_Q1": res["delta_q4_q1"],
            "method": res.get("method", "GAM spline"),
            "spline_df": SPLINE_DF if res.get("method", "GAM spline") != "LOWESS" else np.nan,
            "n_bootstrap": N_BOOT,
            "n_permutations": N_PERM,
            "prediction_domain": "x 1st-99th percentile",
        })

    out = pd.DataFrame(rows)
    out_file = os.path.join(OUT_DIR, "figure_02_regional_model_summary_dhw_hhw_contrast_1990_2024.csv")
    out.to_csv(out_file, index=False)
    print(f"[OK] Saved regional GAM summary: {out_file}")

    return results


# ============================================================
# Supplementary Tables S5-S8
# ============================================================

SUPP_RESPONSE = DRY_SHIFT_ALIAS
SUPP_RESPONSE_UNITS = "Tmax-standardized severity decade-1"

SUPP_PREDICTORS = {
    "agri_gain_pct_points": ("Agricultural expansion, 1990–2024", "recent_change", 1),
    "veg_loss_pct_points": ("Native vegetation loss, 1990–2024", "recent_change", 1),
    "agro_pct_2024": ("Agricultural/farming extent in 2024", "cumulative_state", 1),
    "native_pct_2024": ("Native vegetation cover in 2024", "cumulative_state", -1),
    "transformed_non_native_pct_2024": ("Transformed/non-native land fraction in 2024", "cumulative_state", 1),
}


def _weighted_summary(g, col):
    values = pd.to_numeric(g[col], errors="coerce").to_numpy(float)
    weights = pd.to_numeric(g["total_area_2024_ha"], errors="coerce").to_numpy(float)
    q25 = weighted_quantile(values, weights, 0.25)
    q50 = weighted_quantile(values, weights, 0.50)
    q75 = weighted_quantile(values, weights, 0.75)
    return q50, q25, q75, q75 - q25, weighted_mean_values(values, weights)


def make_s5(mun):
    rows = []
    for group_type, col in [
        ("analytical_region", "focus_region"),
        ("dominant_biome", "dominant_biome"),
    ]:
        for name, g in mun.groupby(col, dropna=False):
            if pd.isna(name) or str(name) in {"", "Other"}:
                continue
            area = pd.to_numeric(g["total_area_2024_ha"], errors="coerce")
            hotspot = pd.to_numeric(
                g["dry_hot_hotspot"], errors="coerce"
            ).fillna(0).astype(int).eq(1)
            response = pd.to_numeric(g[SUPP_RESPONSE], errors="coerce")
            total_area = float(area.sum())
            hotspot_area = float(area[hotspot].sum())
            rows.append({
                "group_type": group_type,
                "region_or_biome": str(name),
                "n_municipalities": int(len(g)),
                "n_hotspot_municipalities": int(hotspot.sum()),
                "municipality_hotspot_percent": 100.0 * float(hotspot.mean()),
                "area_total_2024_ha": total_area,
                "area_hotspot_2024_ha": hotspot_area,
                "area_hotspot_percent": (
                    100.0 * hotspot_area / total_area if total_area > 0 else np.nan
                ),
                "median_DHW_minus_HHW_TmaxOnly_hotspots": weighted_quantile(
                    response[hotspot].to_numpy(float),
                    area[hotspot].to_numpy(float),
                    0.50,
                ),
                "hotspot_definition": (
                    f"{DRY_SHIFT_SOURCE_VAR} > {DRY_SHIFT_THRESHOLD:g}; "
                    f"{DHW_COMMON_TREND_VAR} > 0; "
                    f"DHW significant-positive grid-area fraction >= "
                    f"{MUNICIPAL_SIGPOS_FRACTION_THRESHOLD:.2f}"
                ),
                "units": SUPP_RESPONSE_UNITS,
                "significance_note": (
                    "The municipality support criterion is based on the weighted "
                    "fraction of ERA5 cells with positive DHW Tmax-only trend and "
                    "p <= 0.05; no municipal mean or median p-value is used."
                ),
            })
    out = pd.DataFrame(rows)
    out.to_excel(os.path.join(OUT_DIR, "Supplementary_Table_S5.xlsx"), index=False)
    out.to_csv(os.path.join(OUT_DIR, "Supplementary_Table_S5.csv"), index=False)
    print("[OK] Supplementary Table S5")
    return out


def make_s6(mun):
    rows = []
    variables = [
        SUPP_RESPONSE,
        DHW_COMMON_TREND_VAR,
        HHW_COMMON_TREND_VAR,
        "transformed_non_native_pct_2024",
        "agro_pct_2024",
        "native_pct_2024",
    ]
    for region in REGION_ORDER:
        g = mun[mun["focus_region"] == region].copy()
        if g.empty:
            continue
        row = {
            "region": region,
            "n_municipalities": int(len(g)),
            "area_2024_ha": float(
                pd.to_numeric(g["total_area_2024_ha"], errors="coerce").sum()
            ),
        }
        for var in variables:
            med, q25, q75, iqr, mean = _weighted_summary(g, var)
            prefix = DRY_SHIFT_SOURCE_VAR if var == SUPP_RESPONSE else var
            row[f"{prefix}_median"] = med
            row[f"{prefix}_q25"] = q25
            row[f"{prefix}_q75"] = q75
            row[f"{prefix}_iqr"] = iqr
            row[f"{prefix}_mean"] = mean

        area = pd.to_numeric(g["total_area_2024_ha"], errors="coerce")
        hotspot = pd.to_numeric(
            g["dry_hot_hotspot"], errors="coerce"
        ).fillna(0).astype(int).eq(1)
        row["hotspot_municipality_percent"] = 100.0 * float(hotspot.mean())
        row["hotspot_area_percent"] = (
            100.0 * float(area[hotspot].sum()) / float(area.sum())
            if float(area.sum()) > 0 else np.nan
        )
        row["contrast_definition"] = (
            f"{DHW_COMMON_TREND_VAR} - {HHW_COMMON_TREND_VAR}"
        )
        row["contrast_units"] = SUPP_RESPONSE_UNITS
        rows.append(row)

    out = pd.DataFrame(rows)
    out.to_excel(os.path.join(OUT_DIR, "Supplementary_Table_S6.xlsx"), index=False)
    out.to_csv(os.path.join(OUT_DIR, "Supplementary_Table_S6.csv"), index=False)
    print("[OK] Supplementary Table S6")
    return out


def _bootstrap_weighted_mean(values, weights, rng):
    values = np.asarray(values, float)
    weights = np.asarray(weights, float)
    ok = np.isfinite(values) & np.isfinite(weights) & (weights > 0)
    values, weights = values[ok], weights[ok]
    if len(values) < 10:
        return np.nan, np.nan
    idx = np.arange(len(values))
    boot = np.empty(N_BOOT, float)
    for b in range(N_BOOT):
        s = rng.choice(idx, len(idx), replace=True)
        boot[b] = weighted_mean_values(values[s], weights[s])
    return tuple(np.nanpercentile(boot, [2.5, 97.5]))


def make_s7(mun):
    rows = []
    seed_offset = 0

    for stratum_type, stratum_col in [
        ("dominant_biome", "dominant_biome"),
        ("focus_region", "focus_region"),
    ]:
        for predictor, (label, predictor_class, expected_direction) in SUPP_PREDICTORS.items():
            for stratum, g0 in mun.groupby(stratum_col, dropna=False):
                if pd.isna(stratum) or str(stratum) in {"", "Other"}:
                    continue

                d = g0[[predictor, SUPP_RESPONSE, "total_area_2024_ha"]].copy()
                for c in d.columns:
                    d[c] = pd.to_numeric(d[c], errors="coerce")
                d = d.dropna()
                d = d[d["total_area_2024_ha"] > 0].copy()
                if len(d) < 40:
                    continue

                x = d[predictor].to_numpy(float)
                y = d[SUPP_RESPONSE].to_numpy(float)
                w = d["total_area_2024_ha"].to_numpy(float)

                q25 = weighted_quantile(x, w, 0.25)
                q75 = weighted_quantile(x, w, 0.75)
                low = d[d[predictor] <= q25].copy()
                high = d[d[predictor] >= q75].copy()
                if len(low) < 10 or len(high) < 10:
                    continue

                low_mean = weighted_mean(low, SUPP_RESPONSE)
                high_mean = weighted_mean(high, SUPP_RESPONSE)
                contrast = high_mean - low_mean

                rng = np.random.default_rng(RANDOM_SEED + seed_offset)
                seed_offset += 1
                low_lo, low_hi = _bootstrap_weighted_mean(
                    low[SUPP_RESPONSE], low["total_area_2024_ha"], rng
                )
                high_lo, high_hi = _bootstrap_weighted_mean(
                    high[SUPP_RESPONSE], high["total_area_2024_ha"], rng
                )

                low_y = low[SUPP_RESPONSE].to_numpy(float)
                low_w = low["total_area_2024_ha"].to_numpy(float)
                high_y = high[SUPP_RESPONSE].to_numpy(float)
                high_w = high["total_area_2024_ha"].to_numpy(float)
                boot_delta = np.empty(N_BOOT, float)
                for b in range(N_BOOT):
                    il = rng.choice(np.arange(len(low)), len(low), replace=True)
                    ih = rng.choice(np.arange(len(high)), len(high), replace=True)
                    boot_delta[b] = (
                        weighted_mean_values(high_y[ih], high_w[ih])
                        - weighted_mean_values(low_y[il], low_w[il])
                    )
                delta_lo, delta_hi = np.nanpercentile(
                    boot_delta, [2.5, 97.5]
                )

                rho, p_perm = weighted_spearman(
                    x, y, w,
                    n_perm=N_PERM,
                    seed=RANDOM_SEED + seed_offset,
                )

                rows.append({
                    "stratum_type": stratum_type,
                    "stratum": str(stratum),
                    "predictor": predictor,
                    "predictor_label": label,
                    "predictor_class": predictor_class,
                    "expected_direction": expected_direction,
                    "n_total": int(len(d)),
                    "n_low_q1": int(len(low)),
                    "n_high_q4": int(len(high)),
                    "predictor_q25": q25,
                    "predictor_q75": q75,
                    "low_q1_response_mean": low_mean,
                    "low_q1_response_ci95_low": low_lo,
                    "low_q1_response_ci95_high": low_hi,
                    "high_q4_response_mean": high_mean,
                    "high_q4_response_ci95_low": high_lo,
                    "high_q4_response_ci95_high": high_hi,
                    "contrast_high_minus_low": contrast,
                    "contrast_ci95_low": delta_lo,
                    "contrast_ci95_high": delta_hi,
                    "contrast_directionally_consistent": int(
                        np.sign(contrast) == np.sign(expected_direction)
                    ),
                    "weighted_spearman_rho": rho,
                    "weighted_spearman_p_permutation": p_perm,
                    "n_permutations": N_PERM,
                    "response": DRY_SHIFT_SOURCE_VAR,
                    "response_units": SUPP_RESPONSE_UNITS,
                })

    out = pd.DataFrame(rows)
    out.to_excel(os.path.join(OUT_DIR, "Supplementary_Table_S7.xlsx"), index=False)
    out.to_csv(os.path.join(OUT_DIR, "Supplementary_Table_S7.csv"), index=False)
    print("[OK] Supplementary Table S7")
    return out


def make_s8(mun):
    rows = []

    for stratum_type, stratum_col in [
        ("dominant_biome", "dominant_biome"),
        ("focus_region", "focus_region"),
    ]:
        for predictor, (label, predictor_class, expected_direction) in SUPP_PREDICTORS.items():
            d = mun[
                [stratum_col, predictor, SUPP_RESPONSE, "total_area_2024_ha"]
            ].copy()

            for c in [predictor, SUPP_RESPONSE, "total_area_2024_ha"]:
                d[c] = pd.to_numeric(d[c], errors="coerce")
            d = d.dropna()
            d = d[
                (d["total_area_2024_ha"] > 0)
                & ~d[stratum_col].astype(str).isin(["", "Other"])
            ].copy()
            if len(d) < 40:
                continue

            d["x_anom"] = np.nan
            d["y_anom"] = np.nan

            for _, idx in d.groupby(stratum_col).groups.items():
                sub = d.loc[idx]
                w = sub["total_area_2024_ha"].to_numpy(float)
                d.loc[idx, "x_anom"] = (
                    sub[predictor]
                    - weighted_mean_values(sub[predictor], w)
                )
                d.loc[idx, "y_anom"] = (
                    sub[SUPP_RESPONSE]
                    - weighted_mean_values(sub[SUPP_RESPONSE], w)
                )

            sx = float(np.nanstd(d["x_anom"].to_numpy(float), ddof=1))
            if not np.isfinite(sx) or sx <= 0:
                continue
            d["x_anom_sd"] = d["x_anom"] / sx

            X = sm.add_constant(d[["x_anom_sd"]])
            y = d["y_anom"].to_numpy(float)
            fit_w = np.sqrt(d["total_area_2024_ha"].to_numpy(float))
            fit_w = fit_w / np.nanmean(fit_w)

            fit = sm.WLS(y, X, weights=fit_w).fit(cov_type="HC3")
            coef = float(fit.params["x_anom_sd"])
            ci = fit.conf_int().loc["x_anom_sd"].to_numpy(float)

            rho, p_perm = weighted_spearman(
                d["x_anom"].to_numpy(float),
                d["y_anom"].to_numpy(float),
                d["total_area_2024_ha"].to_numpy(float),
                n_perm=N_PERM,
                seed=RANDOM_SEED + len(d) + len(predictor),
            )

            rows.append({
                "stratum_type": stratum_type,
                "predictor": predictor,
                "predictor_label": label,
                "predictor_class": predictor_class,
                "expected_direction": expected_direction,
                "n": int(len(d)),
                "coef_per_1sd_within_stratum_anomaly": coef,
                "se_HC3": float(fit.bse["x_anom_sd"]),
                "t_HC3": float(fit.tvalues["x_anom_sd"]),
                "p_HC3": float(fit.pvalues["x_anom_sd"]),
                "ci95_low": float(ci[0]),
                "ci95_high": float(ci[1]),
                "r2": float(fit.rsquared),
                "weighted_spearman_rho": rho,
                "weighted_spearman_p_permutation": p_perm,
                "n_permutations": N_PERM,
                "directionally_consistent": int(
                    np.sign(coef) == np.sign(expected_direction)
                ),
                "response": DRY_SHIFT_SOURCE_VAR,
                "response_units": SUPP_RESPONSE_UNITS,
                "model_note": (
                    "Within-stratum anomaly WLS with weights proportional to the square root "
                    "of municipal area and HC3 heteroscedasticity-robust standard errors; "
                    "spatial association, not causal attribution."
                ),
            })

    out = pd.DataFrame(rows)
    out.to_excel(os.path.join(OUT_DIR, "Supplementary_Table_S8.xlsx"), index=False)
    out.to_csv(os.path.join(OUT_DIR, "Supplementary_Table_S8.csv"), index=False)
    print("[OK] Supplementary Table S8")
    return out


def build_supplementary_tables_s5_s8(mun):
    print("[INFO] Building Supplementary Tables S5-S8.")
    s5 = make_s5(mun)
    s6 = make_s6(mun)
    s7 = make_s7(mun)
    s8 = make_s8(mun)

    combined = os.path.join(
        OUT_DIR, "Supplementary_Tables_S5_S8.xlsx"
    )
    with pd.ExcelWriter(combined) as writer:
        s5.to_excel(writer, sheet_name="S5_hotspots", index=False)
        s6.to_excel(writer, sheet_name="S6_regions", index=False)
        s7.to_excel(writer, sheet_name="S7_high_low", index=False)
        s8.to_excel(writer, sheet_name="S8_within_stratum", index=False)
    print(f"[OK] Combined S5-S8 workbook: {combined}")
    return s5, s6, s7, s8


# ============================================================
# Plotting
# ============================================================

def add_colorbar(fig, ax, cmap, norm, label, ticks=None, ticklabels=None):
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])

    divider = make_axes_locatable(ax)
    cax = divider.append_axes("right", size="3.0%", pad=0.03)
    cb = fig.colorbar(sm, cax=cax, ticks=ticks)
    cb.set_label(label, fontsize=11)
    cb.ax.tick_params(labelsize=11)
    if ticklabels is not None:
        cb.ax.set_yticklabels(ticklabels)


def add_stippling(ax, gdf):
    stip = gdf[gdf["dry_shift_stipple"] == True].copy()
    if stip.empty:
        return
    pts = stip.geometry.representative_point()
    ax.scatter(pts.x, pts.y, s=1.2, c="black", alpha=0.55, linewidths=0, zorder=5)


def plot_map(ax, gdf, column, title, cmap, norm, cbar_label, stipple=False,
             ticks=None, ticklabels=None):
    vals = pd.to_numeric(gdf[column], errors="coerce")
    valid = gdf[np.isfinite(vals)].copy()

    gdf.plot(ax=ax, color="0.94", edgecolor="none", linewidth=0, zorder=1)
    valid.plot(
        ax=ax,
        column=column,
        cmap=cmap,
        norm=norm,
        linewidth=0.03,
        edgecolor="0.75",
        zorder=2,
    )
    gdf.boundary.plot(ax=ax, color="0.55", linewidth=0.025, zorder=3)

    if stipple:
        add_stippling(ax, gdf)

    ax.set_xlim(LON_MIN, LON_MAX)
    ax.set_ylim(LAT_MIN, LAT_MAX)
    ax.set_axis_off()
    ax.set_title(title, fontsize=13, fontweight="bold", pad=5)

    add_colorbar(ax.figure, ax, cmap, norm, cbar_label, ticks=ticks, ticklabels=ticklabels)


def plot_hotspot_map(ax, gdf):
    """
    publication-style hotspot panel:
    non-hotspot municipalities are shown in grey;
    hotspot municipalities are coloured continuously by DHW−HHW magnitude.
    """
    gdf.plot(ax=ax, color="0.93", edgecolor="none", linewidth=0, zorder=1)

    hotspots = gdf[np.isfinite(pd.to_numeric(gdf["dry_hot_hotspot_intensity"], errors="coerce"))].copy()

    if not hotspots.empty:
        hotspots.plot(
            ax=ax,
            column="dry_hot_hotspot_intensity",
            cmap=plt.cm.Reds,
            norm=Normalize(vmin=DRY_SHIFT_THRESHOLD, vmax=DRY_SHIFT_VMAX),
            linewidth=0.035,
            edgecolor="0.70",
            zorder=2,
        )

    gdf.boundary.plot(ax=ax, color="0.72", linewidth=0.025, zorder=3)

    ax.set_xlim(LON_MIN, LON_MAX)
    ax.set_ylim(LAT_MIN, LAT_MAX)
    ax.set_axis_off()
    ax.set_title(
        f"(c) Diagnostic dry-hot hotspots\nDHW−HHW > {DRY_SHIFT_THRESHOLD:g}",
        fontsize=13,
        fontweight="bold",
        pad=5,
    )

    add_colorbar(
        ax.figure,
        ax,
        plt.cm.Reds,
        Normalize(vmin=DRY_SHIFT_THRESHOLD, vmax=DRY_SHIFT_VMAX),
        "DHW−HHW Tmax-standardized\nseverity decade$^{-1}$",
    )

    ax.text(
        0.02,
        0.02,
        "grey = outside hotspot criterion",
        transform=ax.transAxes,
        fontsize=12,
        ha="left",
        va="bottom",
        bbox=dict(facecolor="white", edgecolor="none", alpha=0.75, pad=1.5),
    )


def add_rug(ax, x_obs, color="0.1"):
    x_obs = np.asarray(x_obs, dtype=float)
    x_obs = x_obs[np.isfinite(x_obs)]

    if x_obs.size == 0:
        return

    ymin, ymax = ax.get_ylim()
    y_rug = ymin + 0.03 * (ymax - ymin)

    if len(x_obs) > 1500:
        rng = np.random.default_rng(RANDOM_SEED)
        x_obs = rng.choice(x_obs, size=1500, replace=False)

    ax.plot(
        x_obs,
        np.full_like(x_obs, y_rug),
        "|",
        color=color,
        alpha=0.22,
        markersize=4,
        markeredgewidth=0.45,
        zorder=4,
    )


def plot_regional_gam(ax, res, region):
    color = "#D95F02"

    if res is None:
        ax.text(0.5, 0.5, "Insufficient data", transform=ax.transAxes,
                ha="center", va="center", fontsize=11)
        ax.set_title(region, fontsize=12, fontweight="bold")
        return

    ax.plot(res["x"], res["yhat"], color=color, linewidth=1.9)
    if np.isfinite(res["lo"]).any() and np.isfinite(res["hi"]).any():
        ax.fill_between(res["x"], res["lo"], res["hi"], color=color, alpha=0.20)

    ax.axhline(0, color="0.35", linestyle="--", linewidth=0.7)
    ax.grid(True, alpha=0.25, linewidth=0.35)
    method = res.get("method", "GAM spline")
    ax.set_title(f"{region} ({method})", fontsize=13, fontweight="bold")
    ax.tick_params(labelsize=12)

    add_rug(ax, res.get("x_obs", []), color=color)

    txt = f"N={res['n']}\nρw={res['rho']:.2f}\nΔ={res['delta_q4_q1']:.2f}"
    ax.text(
        0.04, 0.95, txt,
        transform=ax.transAxes,
        ha="left", va="top",
        fontsize=11,
        bbox=dict(facecolor="white", edgecolor="0.7", alpha=0.85),
    )


def plot_regional_dry_shift(ax, summary):
    data = summary.set_index("region").reindex(REGION_ORDER)

    y = np.arange(len(REGION_ORDER))
    med = pd.to_numeric(data["dry_minus_humid_intensity_trend_median"], errors="coerce").values
    q25 = pd.to_numeric(data["dry_minus_humid_intensity_trend_p25"], errors="coerce").values
    q75 = pd.to_numeric(data["dry_minus_humid_intensity_trend_p75"], errors="coerce").values

    colors = ["#B2182B" if np.isfinite(v) and v >= 0 else "#2C7BB6" for v in med]

    for yi, m, l, h, col in zip(y, med, q25, q75, colors):
        if not np.isfinite(m):
            continue
        if np.isfinite(l) and np.isfinite(h):
            ax.plot([l, h], [yi, yi], color=col, alpha=0.28, linewidth=9,
                    solid_capstyle="round", zorder=1)
            ax.plot([l, h], [yi, yi], color=col, alpha=0.75, linewidth=1.3,
                    solid_capstyle="round", zorder=2)
        ax.scatter(m, yi, s=45, color=col, edgecolor="0.15", linewidth=0.5, zorder=3)

    ax.axvline(0, color="0.2", linewidth=0.8)
    ax.grid(axis="x", alpha=0.25, linewidth=0.4)
    ax.set_yticks(y)
    ax.set_yticklabels(REGION_ORDER, fontsize=11)
    ax.invert_yaxis()
    ax.set_xlabel("DHW − HHW intensity trend\n(Tmax-standardized severity decade$^{-1}$)", fontsize=11)
    ax.set_title("(e) Regional DHW−HHW contrast\nmedian and interquartile range", fontsize=13, fontweight="bold", pad=5)
    ax.set_xlim(-1, 6.5)

    ax.text(0.02, 0.03, "positive = stronger dry-hot amplification", transform=ax.transAxes,
            fontsize=11, ha="left", va="bottom")

    # Compact association annotation.
    mechanism = (
        "transformed land and atmospheric drying\n"
        "co-vary with stronger DHW−HHW"
    )
    ax.text(
        0.98, 0.97, mechanism,
        transform=ax.transAxes,
        ha="right",
        va="top",
        fontsize=11,
        linespacing=1.25,
        bbox=dict(facecolor="white", edgecolor="0.75", boxstyle="round,pad=0.35", alpha=0.90),
    )


def plot_figure(gdf, gam_results, summary):
    print("[INFO] Plotting Figure 02.")

    fig = plt.figure(figsize=(20, 17))
    gs = GridSpec(
        2, 3,
        left=0.035,
        right=0.98,
        top=0.895,
        bottom=0.135,
        wspace=0.28,
        hspace=0.36,
    )

    ax_a = fig.add_subplot(gs[0, 0])
    ax_b = fig.add_subplot(gs[0, 1])
    ax_c = fig.add_subplot(gs[0, 2])
    ax_d_container = fig.add_subplot(gs[1, 0:2])
    ax_e = fig.add_subplot(gs[1, 2])

    plot_map(
        ax_a,
        gdf,
        "dry_minus_humid_intensity_trend",
        "(a) Preferential dry-hot amplification\nDHW − HHW",
        CMAP_DRYSHIFT,
        TwoSlopeNorm(vmin=DRY_SHIFT_VMIN, vcenter=DRY_SHIFT_VCENTER, vmax=DRY_SHIFT_VMAX),
        "Tmax-standardized severity decade$^{-1}$",
        stipple=True,
    )

    plot_map(
        ax_b,
        gdf,
        "transformed_non_native_pct_2024",
        "(b) Cumulative transformed land fraction\n2024",
        CMAP_AGRI,
        Normalize(vmin=TRANSFORMED_VMIN, vmax=TRANSFORMED_VMAX),
        "% municipal area",
        stipple=False,
    )

    plot_hotspot_map(ax_c, gdf)

    ax_d_container.axis("off")
    # Place the row heading in the whitespace between the map row and the small multiples.
    # This avoids overlap with the individual regional subplot titles.
    fig.text(
        0.315, 0.495,
        "(d) Region-specific associations: transformed land vs DHW−HHW",
        fontsize=13,
        fontweight="bold",
        ha="center",
        va="center",
    )

    sub = GridSpecFromSubplotSpec(
        2, 2,
        subplot_spec=gs[1, 0:2],
        wspace=0.55,
        hspace=0.70
    )

    gam_axes = []
    for i, region in enumerate(GAM_REGIONS):
        ax = fig.add_subplot(sub[i // 2, i % 2])
        gam_axes.append(ax)
        plot_regional_gam(ax, gam_results.get(region), region)

    for ax in gam_axes[2:]:
        ax.set_xlabel("Transformed/non-native land fraction\n(% municipal area, 2024)", fontsize=12)
    for ax in [gam_axes[0], gam_axes[2]]:
        ax.set_ylabel("DHW − HHW intensity trend\n(Tmax-standardized severity decade$^{-1}$)", fontsize=12)

    # Harmonize y-limits across small multiples.
    all_y = []
    for res in gam_results.values():
        if res is None:
            continue
        all_y.extend(np.asarray(res["lo"], dtype=float)[np.isfinite(res["lo"])])
        all_y.extend(np.asarray(res["hi"], dtype=float)[np.isfinite(res["hi"])])
    if all_y:
        ymin = max(-1.5, np.nanpercentile(all_y, 2) - 0.5)
        ymax = min(8.0, np.nanpercentile(all_y, 98) + 0.5)
        for ax in gam_axes:
            ax.set_ylim(ymin, ymax)
            # Rug must be redrawn after y-limits are harmonized.
            # Clear and replot would be expensive; instead the initial rug is
            # already lifted and remains readable. This harmonization does not
            # affect the curve validity.

    plot_regional_dry_shift(ax_e, summary)

    #fig.suptitle(
    #    f"Thermodynamic divergence toward dry-hot heatwaves under land transformation ({YEAR0}–{YEAR1})",
    #    fontsize=15.5,
    #    fontweight="bold",
    #    y=0.972,
    #)

    #foot = (
    #    "Land-cover state: MapBiomas Collection 10.1. Panel b shows transformed/non-native land fraction in 2024 (=100 − native vegetation cover).\n"
    #    "Heatwave trends: ERA5 hourly data (1990–2024), Theil–Sen slopes. DHW−HHW uses common Tmax-standardized severity. "
    #    "Hotspots: DHW−HHW > 4, positive municipal DHW Tmax-only trend, and ≥50% significant-positive DHW grid-area support. Curves show regional GAM/LOWESS associations."
    #)

    #fig.text(
    #    0.035,
    #    0.055,
    #    foot,
    #    fontsize=8.0,
    #    ha="left",
    #    va="bottom",
    #    linespacing=1.28,
    #)

    out_base = os.path.join(OUT_DIR, "figure_02_land_transformation")
    fig.savefig(out_base + ".jpeg", dpi=500, bbox_inches="tight", facecolor="white")
    fig.savefig(out_base + ".pdf", dpi=500, bbox_inches="tight", facecolor="white")
    plt.close(fig)

    print(f"[OK] Saved {out_base}.jpeg")
    print(f"[OK] Saved {out_base}.pdf")


# ============================================================
# Main
# ============================================================

def main():
    args = parse_args()
    configure_paths(args)

    print("=" * 82)
    print("FIGURE 02 — DRY-HOT AMPLIFICATION AND LAND TRANSFORMATION")
    print("=" * 82)
    print(f"Figure 01 trends : {ERA5_TRENDS_NC}")
    print(f"MapBiomas workbook         : {COVERAGE_XLSX}")
    print(f"Municipality shapefile     : {MUNICIPALITY_SHP}")
    print(f"Output directory           : {OUT_DIR}")
    print(
        "DHW-HHW metric             : "
        "DHW_minus_HHW_TmaxOnly_intensity_trend_decade"
    )
    print("Analysis                  : common Tmax-only DHW-HHW contrast")
    print("=" * 82)

    mb_raw = read_mapbiomas()
    mb = build_landcover_municipality_biome(mb_raw)

    gdf_mun = load_municipality_geometry()
    mun_table = aggregate_to_municipality(mb)
    mun_table = extract_era5_trends(mun_table, gdf_mun)
    gdf = merge_geometry(mun_table, gdf_mun)

    summary = build_region_summary(mun_table)
    gam_results = run_regional_gam_models(mun_table)

    # S5-S8 use the same municipality table and common-scale DHW-HHW contrast as Figure 02.
    build_supplementary_tables_s5_s8(mun_table)

    plot_figure(gdf, gam_results, summary)

    print("\n[DONE]")
    print("Outputs saved in:")
    print(" ", OUT_DIR)


if __name__ == "__main__":
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        main()
