#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Figure 01 supplementary robustness workflow.

Purpose
-------
Generate Supplementary Tables S1–S4 using the same definitions, trend methods,
and common-scale comparison adopted for Figure 01.

The script uses Figure 01 products and applies the same scientific configuration
and trend-significance methodology.

Tables
------
S1
    National and biome summaries of the primary Figure 01 regime-specific
    frequency, duration and intensity trends.

S2
    National and biome summaries of the unit-consistent HHW–DHW intensity
    contrast:
        DHW_minus_HHW_TmaxOnly_intensity_trend_decade
    This uses the common Tmax-only standardized-severity scale generated by the
    Figure 01 workflow. The direct subtraction of primary DHW and HHW
    intensity metrics is explicitly prohibited.

S3
    Sensitivity of the same unit-consistent HHW–DHW contrast to:
      - DHW VPD threshold P70;
      - DHW VPD threshold P80;
      - HHW Twbmax threshold P90;
      - minimum event duration 2 days;
      - minimum event duration 4 days.
    In every sensitivity scenario, direct HHW–DHW comparison is computed from
    the same Tmax-only standardized severity for both regimes.

S4
    Temporal robustness of the PRIMARY DHW intensity metric:
      - 1990–2024;
      - truncated at 2022;
      - truncated at 2023;
      - leave-one-year-out diagnostics.
    The primary DHW intensity definition is unchanged:
        0.5*z+(Tmax) + 0.5*z+(VPD).

Scientific consistency
----------------------
Analysis period
    1990–2024.
Baseline
    1991–2020.
Primary minimum event duration
    3 consecutive days.
Primary DHW definition
    Tmax >= local P95 AND VPDmean >= local P75.
Primary HHW definition
    Twbmax >= local P95.
Common HHW–DHW comparison intensity
    Sum z+(Tmax) over persistent event days.
Trend magnitude
    Theil-Sen median slope per decade.
Significance
    Original two-sided Mann-Kendall when detrended lag-1 rank autocorrelation is
    not significant; otherwise Hamed-Rao variance-corrected Mann-Kendall lag 1.
Annual validity
    >=300 valid days/year and >=20 valid years.

Important
---------
The primary Figure 01 regime-specific intensities are intentionally preserved:
  - HW/HHW: cumulative degree-Celsius-day exceedance;
  - DHW/CHW: dimensionless standardized severity.

Those regime-specific intensities may be summarized individually in S1, but
primary DHW and HHW intensity fields MUST NOT be subtracted. S2 and S3 use only
the common Tmax-only standardized intensity scale.

Inputs
------
--figure1-output-dir
    Root output directory produced by corrected figure_01_heatwave_trends.py.
    Expected:
      data/figure_01_heatwave_trends_1990_2024.nc
      data/figure_01_annual_heatwave_metrics_1990_2024.nc
      cache/figure_01_heatwave_thresholds_1991_2020.nc
      cache/era5_daily/ERA5_daily_Brazil_YYYY.nc

--brazil-shapefile
    Brazil/UF boundary shapefile.

--biomes-shapefile
    Optional Brazilian-biomes shapefile. If omitted, only Brazil summaries are
    generated.

--output-dir
    Optional supplementary output directory. Defaults to:
      <figure1-output-dir>/supplementary

Outputs
-------
Supplementary_Table_S1.csv/.xlsx
Supplementary_Table_S2.csv/.xlsx
Supplementary_Table_S3.csv/.xlsx
Supplementary_Table_S4.csv/.xlsx
Diagnostic_Table_threshold_duration_sensitivity_all_metrics.csv
figure_01_sensitivity_tmaxonly_<scenario>.nc
figure_01_dhw_intensity_extreme_year_robustness.nc
README_figure_01_supplementary_robustness.txt

Usage
-----
python figure_01_supplementary_robustness.py \
    --figure1-output-dir /path/to/figure_01_outputs \
    --brazil-shapefile /path/to/brazil_boundary.shp \
    --biomes-shapefile /path/to/brazil_biomes.shp \
    --output-dir ./outputs/figure_01_supplementary
"""

import os
import re
import glob
import argparse
import warnings
import unicodedata
from pathlib import Path


import numpy as np
import pandas as pd
import xarray as xr
import geopandas as gpd
from shapely.geometry import Point
from scipy.stats import linregress, norm, theilslopes

try:
    import pymannkendall as mk
    _HAS_PYMK = True
except Exception:
    _HAS_PYMK = False


# ============================================================
# Fixed scientific configuration
# ============================================================

START_YEAR = 1990
END_YEAR = 2024
BASE_START = 1991
BASE_END = 2020

ROLLING_WINDOW_DAYS = 31
PRIMARY_MIN_LEN = 3

MIN_VALID_DAYS_PER_YEAR = 300
MIN_VALID_YEARS_FOR_TREND = 20
P_THRESHOLD = 0.05

Z_CLIP_MIN = -5.0
Z_CLIP_MAX = 5.0

AUTOCORR_ALPHA = 0.05
TREND_SIGNIFICANCE_VERSION = "Theil-Sen + conditional Hamed-Rao MK lag1 v1"

KINDS = ["HW", "HHW", "DHW", "CHW"]
METRICS = ["frequency", "duration", "intensity"]

SENSITIVITY_SCENARIOS = [
    {
        "scenario": "primary_P75_P95_minlen3",
        "description": "Primary HHW-DHW contrast",
        "min_len": 3,
        "dhw_vpd_percentile": 75.0,
        "hhw_twb_percentile": 95.0,
        "compute_from_main": True,
    },
    {
        "scenario": "DHW_VPD_P70_minlen3",
        "description": "DHW VPD threshold P70; HHW P95; min length 3",
        "min_len": 3,
        "dhw_vpd_percentile": 70.0,
        "hhw_twb_percentile": 95.0,
        "compute_from_main": False,
    },
    {
        "scenario": "DHW_VPD_P80_minlen3",
        "description": "DHW VPD threshold P80; HHW P95; min length 3",
        "min_len": 3,
        "dhw_vpd_percentile": 80.0,
        "hhw_twb_percentile": 95.0,
        "compute_from_main": False,
    },
    {
        "scenario": "HHW_TWB_P90_minlen3",
        "description": "HHW Twbmax threshold P90; DHW P75; min length 3",
        "min_len": 3,
        "dhw_vpd_percentile": 75.0,
        "hhw_twb_percentile": 90.0,
        "compute_from_main": False,
    },
    {
        "scenario": "primary_thresholds_minlen2",
        "description": "Primary thresholds; minimum event duration 2 days",
        "min_len": 2,
        "dhw_vpd_percentile": 75.0,
        "hhw_twb_percentile": 95.0,
        "compute_from_main": False,
    },
    {
        "scenario": "primary_thresholds_minlen4",
        "description": "Primary thresholds; minimum event duration 4 days",
        "min_len": 4,
        "dhw_vpd_percentile": 75.0,
        "hhw_twb_percentile": 95.0,
        "compute_from_main": False,
    },
]


# ============================================================
# NetCDF backend helpers
# ============================================================

def _available_netcdf_engines():
    engines = xr.backends.list_engines()
    return [name for name in ("h5netcdf", "netcdf4", "scipy") if name in engines]


def safe_open_dataset(path, *, decode_times=True, chunks=None, **kwargs):
    errors = []
    for engine in _available_netcdf_engines():
        try:
            return xr.open_dataset(
                path,
                engine=engine,
                decode_times=decode_times,
                chunks=chunks,
                **kwargs,
            )
        except Exception as exc:
            errors.append(f"{engine}: {type(exc).__name__}: {exc}")

    raise RuntimeError(
        f"Could not open NetCDF file: {path}\n"
        + "\n".join(errors)
    )


def safe_to_netcdf(ds, path, *, encoding=None, **kwargs):
    errors = []
    engines = _available_netcdf_engines()

    if "h5netcdf" in engines:
        try:
            return ds.to_netcdf(
                path,
                engine="h5netcdf",
                encoding=encoding,
                **kwargs,
            )
        except Exception as exc:
            errors.append(f"h5netcdf: {type(exc).__name__}: {exc}")

    if "netcdf4" in engines:
        try:
            return ds.to_netcdf(
                path,
                engine="netcdf4",
                encoding=encoding,
                **kwargs,
            )
        except Exception as exc:
            errors.append(f"netcdf4: {type(exc).__name__}: {exc}")

    if "scipy" in engines:
        scipy_encoding = None
        if encoding:
            scipy_encoding = {
                var: {
                    k: v
                    for k, v in opts.items()
                    if k in {"dtype", "_FillValue", "scale_factor", "add_offset"}
                }
                for var, opts in encoding.items()
            }
        try:
            return ds.to_netcdf(
                path,
                engine="scipy",
                encoding=scipy_encoding,
                **kwargs,
            )
        except Exception as exc:
            errors.append(f"scipy: {type(exc).__name__}: {exc}")

    raise RuntimeError(
        f"Could not write NetCDF file: {path}\n"
        + "\n".join(errors)
    )


# ============================================================
# Generic utilities
# ============================================================

def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate Figure 01 Supplementary Tables S1-S4."
    )
    parser.add_argument(
        "--figure1-output-dir",
        required=True,
        help="Root output directory produced by figure_01_heatwave_trends.py.",
    )
    parser.add_argument(
        "--brazil-shapefile",
        required=True,
        help="Brazil/UF boundary shapefile.",
    )
    parser.add_argument(
        "--biomes-shapefile",
        default=None,
        help="Optional Brazilian-biomes shapefile.",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Supplementary output directory.",
    )
    parser.add_argument(
        "--recompute-sensitivities",
        action="store_true",
        help="Ignore compatible sensitivity caches and recompute S3 scenarios.",
    )
    parser.add_argument(
        "--recompute-s4",
        action="store_true",
        help="Recompute S4 truncated/LOYO NetCDF.",
    )
    return parser.parse_args()


def configure_paths(args):
    root = Path(args.figure1_output_dir).expanduser().resolve()
    output = (
        Path(args.output_dir).expanduser().resolve()
        if args.output_dir
        else root / "supplementary"
    )
    output.mkdir(parents=True, exist_ok=True)

    paths = {
        "root": root,
        "trends": root / "data" / "figure_01_heatwave_trends_1990_2024.nc",
        "annual": root / "data" / "figure_01_annual_heatwave_metrics_1990_2024.nc",
        "thresholds": root / "cache" / "figure_01_heatwave_thresholds_1991_2020.nc",
        "daily_dir": root / "cache" / "era5_daily",
        "brazil_shp": Path(args.brazil_shapefile).expanduser().resolve(),
        "biomes_shp": (
            Path(args.biomes_shapefile).expanduser().resolve()
            if args.biomes_shapefile else None
        ),
        "output": output,
    }

    for key in ("trends", "annual", "thresholds", "daily_dir", "brazil_shp"):
        if not paths[key].exists():
            raise FileNotFoundError(f"Required input not found: {paths[key]}")

    return paths


def remove_feb29(ds):
    mask = ~((ds.time.dt.month == 2) & (ds.time.dt.day == 29))
    return ds.sel(time=mask)


def ensure_complete_daily_calendar(ds):
    expected = pd.date_range(
        f"{START_YEAR}-01-01",
        f"{END_YEAR}-12-31",
        freq="1D",
    )
    return ds.reindex(time=expected)


def add_noleap_doy(ds):
    dates = pd.to_datetime(ds.time.values)
    doy = []
    for d in dates:
        y0 = pd.Timestamp(f"{d.year}-01-01")
        val = (d - y0).days + 1
        if d.is_leap_year and d.month > 2:
            val -= 1
        doy.append(val)
    return ds.assign_coords(
        doy_noleap=("time", np.asarray(doy, dtype=np.int16))
    )


def normalize_text(x):
    if pd.isna(x):
        return ""
    s = unicodedata.normalize("NFKD", str(x).strip())
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    return re.sub(r"\s+", " ", s).upper()


def detect_biome_name_column(gdf):
    for col in ["Bioma", "BIOMA", "bioma", "NOME", "nome", "NAME", "name"]:
        if col in gdf.columns:
            return col
    for col in gdf.columns:
        if col != "geometry" and str(gdf[col].dtype) == "object":
            return col
    raise ValueError(f"Could not identify biome-name column: {list(gdf.columns)}")


def make_brazil_mask(lats, lons, shp_path):
    uf = gpd.read_file(shp_path).to_crs(epsg=4326)
    geom = uf.dissolve().geometry.iloc[0]
    mask = np.zeros((len(lats), len(lons)), dtype=bool)

    for iy, lat in enumerate(lats):
        points = [Point(float(lon), float(lat)) for lon in lons]
        mask[iy, :] = [
            geom.contains(point) or geom.touches(point)
            for point in points
        ]

    return xr.DataArray(
        mask,
        coords={"lat": lats, "lon": lons},
        dims=("lat", "lon"),
    )


def build_region_masks(lats, lons, brazil_mask, biomes_shp):
    masks = {"Brazil": brazil_mask.astype(bool)}

    if biomes_shp is None:
        return masks
    if not biomes_shp.exists():
        print(f"[WARN] Biomes shapefile not found: {biomes_shp}")
        return masks

    biomes = gpd.read_file(biomes_shp).to_crs(epsg=4326)
    name_col = detect_biome_name_column(biomes)

    lon2d, lat2d = np.meshgrid(lons, lats)
    flat_points = [
        Point(float(x), float(y))
        for x, y in zip(lon2d.ravel(), lat2d.ravel())
    ]

    display_map = {
        "AMAZONIA": "Amazon",
        "AMAZON": "Amazon",
        "CERRADO": "Cerrado",
        "CAATINGA": "Caatinga",
        "MATA ATLANTICA": "Atlantic Forest",
        "ATLANTIC FOREST": "Atlantic Forest",
        "PANTANAL": "Pantanal",
        "PAMPA": "Pampa",
        "PAMPAS": "Pampa",
    }

    for raw_name, sub in biomes.groupby(name_col):
        display = display_map.get(normalize_text(raw_name), str(raw_name))
        geom = sub.dissolve().geometry.iloc[0]
        values = np.array(
            [
                geom.contains(point) or geom.touches(point)
                for point in flat_points
            ],
            dtype=bool,
        ).reshape(len(lats), len(lons))

        values &= brazil_mask.values.astype(bool)

        if values.sum() > 0:
            masks[display] = xr.DataArray(
                values,
                coords={"lat": lats, "lon": lons},
                dims=("lat", "lon"),
            )

    return masks


def area_weights_for_grid(lats, lons):
    w = np.repeat(
        np.cos(np.deg2rad(lats))[:, None],
        len(lons),
        axis=1,
    )
    return xr.DataArray(
        w,
        coords={"lat": lats, "lon": lons},
        dims=("lat", "lon"),
    )


def weighted_quantile(values, weights, q):
    values = np.asarray(values, dtype=float)
    weights = np.asarray(weights, dtype=float)

    ok = np.isfinite(values) & np.isfinite(weights) & (weights > 0)
    if ok.sum() == 0:
        return np.nan

    values = values[ok]
    weights = weights[ok]
    idx = np.argsort(values)
    values = values[idx]
    weights = weights[idx]

    cdf = np.cumsum(weights) / np.sum(weights)
    return float(np.interp(q, cdf, values))


def summarize_map(
    values_da,
    p_da,
    region_masks,
    weights_da,
    *,
    scenario,
    kind,
    metric,
    units,
    significance_field=None,
):
    rows = []

    for region, mask_da in region_masks.items():
        vals = values_da.where(mask_da).values.ravel()
        weights = weights_da.where(mask_da).values.ravel()

        if p_da is None:
            pvals = np.full(vals.shape, np.nan, dtype=float)
        else:
            pvals = p_da.where(mask_da).values.ravel()

        ok = np.isfinite(vals) & np.isfinite(weights) & (weights > 0)
        if ok.sum() == 0:
            continue

        vals = vals[ok]
        weights = weights[ok]
        pvals = pvals[ok]

        pos = vals > 0
        neg = vals < 0
        sig = np.isfinite(pvals) & (pvals <= P_THRESHOLD)

        q25 = weighted_quantile(vals, weights, 0.25)
        med = weighted_quantile(vals, weights, 0.50)
        q75 = weighted_quantile(vals, weights, 0.75)

        rows.append({
            "scenario": scenario,
            "region": region,
            "kind": kind,
            "metric": metric,
            "units": units,
            "significance_field": significance_field or "",
            "n_grid_cells": int(ok.sum()),
            "trend_median": med,
            "trend_q25": q25,
            "trend_q75": q75,
            "trend_iqr": q75 - q25,
            "area_positive_percent": float(
                100.0 * np.sum(weights[pos]) / np.sum(weights)
            ),
            "area_negative_percent": float(
                100.0 * np.sum(weights[neg]) / np.sum(weights)
            ),
            "area_significant_percent": float(
                100.0 * np.sum(weights[sig]) / np.sum(weights)
            ) if p_da is not None else np.nan,
            "area_significant_positive_percent": float(
                100.0 * np.sum(weights[sig & pos]) / np.sum(weights)
            ) if p_da is not None else np.nan,
            "area_significant_negative_percent": float(
                100.0 * np.sum(weights[sig & neg]) / np.sum(weights)
            ) if p_da is not None else np.nan,
        })

    return rows


def save_table(df, output_dir, table_number):
    csv = output_dir / f"Supplementary_Table_S{table_number}.csv"
    xlsx = output_dir / f"Supplementary_Table_S{table_number}.xlsx"

    df.to_csv(csv, index=False)
    df.to_excel(xlsx, index=False)

    print(f"[OK] Saved S{table_number}: {csv}")
    print(f"[OK] Saved S{table_number}: {xlsx}")


# ============================================================
# Trend methodology — identical logic to corrected Figure 01
# ============================================================

def _mk_score_and_variance(y):
    y = np.asarray(y, dtype=float)
    y = y[np.isfinite(y)]
    n = len(y)

    if n < MIN_VALID_YEARS_FOR_TREND:
        return np.nan, np.nan

    s = sum(
        np.sign(y[j] - y[i])
        for i in range(n - 1)
        for j in range(i + 1, n)
    )

    _, counts = np.unique(y, return_counts=True)
    tie_term = sum(
        c * (c - 1) * (2 * c + 5)
        for c in counts
    )
    var_s = (
        n * (n - 1) * (2 * n + 5) - tie_term
    ) / 18.0

    return float(s), float(var_s)


def _mk_p_from_s_var(s, var_s):
    if not np.isfinite(s) or not np.isfinite(var_s) or var_s <= 0:
        return np.nan

    z = (
        (s - np.sign(s)) / np.sqrt(var_s)
        if s != 0 else 0.0
    )
    return float(
        2.0 * (1.0 - norm.cdf(abs(z)))
    )


def mann_kendall_pvalue(y, min_valid_years=MIN_VALID_YEARS_FOR_TREND):
    y = np.asarray(y, dtype=float)
    y = y[np.isfinite(y)]

    if len(y) < min_valid_years:
        return np.nan

    if _HAS_PYMK:
        try:
            return float(mk.original_test(y).p)
        except Exception:
            pass

    # Local calculation needs the same minimum criterion.
    n = len(y)
    s = sum(
        np.sign(y[j] - y[i])
        for i in range(n - 1)
        for j in range(i + 1, n)
    )
    _, counts = np.unique(y, return_counts=True)
    tie_term = sum(
        c * (c - 1) * (2 * c + 5)
        for c in counts
    )
    var_s = (
        n * (n - 1) * (2 * n + 5) - tie_term
    ) / 18.0

    return _mk_p_from_s_var(float(s), float(var_s))


def detrended_lag1_autocorrelation(
    y,
    years,
    alpha=AUTOCORR_ALPHA,
    min_valid_years=MIN_VALID_YEARS_FOR_TREND,
):
    y = np.asarray(y, dtype=float)
    years = np.asarray(years, dtype=float)

    valid = np.isfinite(y) & np.isfinite(years)
    y = y[valid]
    years = years[valid]
    n = len(y)

    if n < min_valid_years or n < 4:
        return np.nan, np.nan, False

    critical = float(
        norm.ppf(1.0 - alpha / 2.0) / np.sqrt(n)
    )

    if np.nanstd(y) <= 1e-12:
        return 0.0, critical, False

    sen = theilslopes(y, years, alpha=0.05)
    slope, intercept = float(sen[0]), float(sen[1])
    residual = y - (intercept + slope * years)

    ranks = (
        pd.Series(residual)
        .rank(method="average")
        .to_numpy(dtype=float)
    )

    if (
        np.nanstd(ranks[:-1]) <= 1e-12
        or np.nanstd(ranks[1:]) <= 1e-12
    ):
        r1 = 0.0
    else:
        r1 = float(
            np.corrcoef(ranks[:-1], ranks[1:])[0, 1]
        )

    significant = bool(
        np.isfinite(r1) and abs(r1) > critical
    )

    return r1, critical, significant


def hamed_rao_mk_pvalue_lag1(
    y,
    years,
    alpha=AUTOCORR_ALPHA,
    min_valid_years=MIN_VALID_YEARS_FOR_TREND,
):
    y = np.asarray(y, dtype=float)
    years = np.asarray(years, dtype=float)

    valid = np.isfinite(y) & np.isfinite(years)
    y = y[valid]
    years = years[valid]
    n = len(y)

    if n < min_valid_years:
        return np.nan

    if _HAS_PYMK:
        try:
            return float(
                mk.hamed_rao_modification_test(
                    y,
                    alpha=alpha,
                    lag=1,
                ).p
            )
        except Exception:
            pass

    # MK S and base variance for available years.
    s = sum(
        np.sign(y[j] - y[i])
        for i in range(n - 1)
        for j in range(i + 1, n)
    )
    _, counts = np.unique(y, return_counts=True)
    tie_term = sum(
        c * (c - 1) * (2 * c + 5)
        for c in counts
    )
    var_s = (
        n * (n - 1) * (2 * n + 5) - tie_term
    ) / 18.0

    if var_s <= 0:
        return np.nan

    sen = theilslopes(y, years, alpha=0.05)
    slope, intercept = float(sen[0]), float(sen[1])
    detrended = y - (intercept + slope * years)

    ranks = (
        pd.Series(detrended)
        .rank(method="average")
        .to_numpy(dtype=float)
    )

    if (
        np.std(ranks[:-1]) <= 1e-12
        or np.std(ranks[1:]) <= 1e-12
    ):
        rho1 = 0.0
    else:
        rho1 = float(
            np.corrcoef(ranks[:-1], ranks[1:])[0, 1]
        )

    critical = float(
        norm.ppf(1.0 - alpha / 2.0) / np.sqrt(n)
    )

    if abs(rho1) <= critical:
        return _mk_p_from_s_var(float(s), float(var_s))

    correction = 1.0 + (
        2.0 * (n - 3) / n
    ) * abs(rho1)
    correction = max(correction, 1.0)

    return _mk_p_from_s_var(
        float(s),
        float(var_s * correction),
    )


def robust_trend(
    y,
    years,
    min_valid_years=MIN_VALID_YEARS_FOR_TREND,
):
    y = np.asarray(y, dtype=float)
    years = np.asarray(years, dtype=float)

    valid = np.isfinite(y) & np.isfinite(years)
    y_valid = y[valid]
    years_valid = years[valid]

    if len(y_valid) < min_valid_years:
        return (
            np.nan, np.nan, np.nan, np.nan,
            np.nan, np.nan, np.nan, np.nan,
        )

    sen = theilslopes(y_valid, years_valid, alpha=0.05)
    sen_slope = float(sen[0] * 10.0)

    original_p = mann_kendall_pvalue(
        y_valid,
        min_valid_years=min_valid_years,
    )

    lag1_r, lag1_critical, lag1_sig = (
        detrended_lag1_autocorrelation(
            y_valid,
            years_valid,
            min_valid_years=min_valid_years,
        )
    )

    if lag1_sig:
        selected_p = hamed_rao_mk_pvalue_lag1(
            y_valid,
            years_valid,
            min_valid_years=min_valid_years,
        )
        method_code = 1.0
    else:
        selected_p = original_p
        method_code = 0.0

    lr = linregress(years_valid, y_valid)
    ols_slope = float(lr.slope * 10.0)
    ols_p = float(lr.pvalue)

    return (
        sen_slope,
        selected_p,
        ols_slope,
        ols_p,
        lag1_r,
        lag1_critical,
        method_code,
        original_p,
    )


# ============================================================
# Event and threshold helpers
# ============================================================

def detect_runs_1d(mask, intensity, years, min_len):
    annual_freq = {
        int(y): 0.0
        for y in range(START_YEAR, END_YEAR + 1)
    }
    annual_days = {
        int(y): 0.0
        for y in range(START_YEAR, END_YEAR + 1)
    }
    annual_intensity = {
        int(y): 0.0
        for y in range(START_YEAR, END_YEAR + 1)
    }

    n = len(mask)
    i = 0

    while i < n:
        if mask[i]:
            j = i
            while j + 1 < n and mask[j + 1]:
                j += 1

            duration = j - i + 1

            if duration >= min_len:
                start_year = int(years[i])
                if START_YEAR <= start_year <= END_YEAR:
                    annual_freq[start_year] += 1.0

                for k in range(i, j + 1):
                    year = int(years[k])
                    if START_YEAR <= year <= END_YEAR:
                        annual_days[year] += 1.0
                        value = intensity[k]
                        if np.isfinite(value) and value > 0:
                            annual_intensity[year] += float(value)

            i = j + 1
        else:
            i += 1

    return annual_freq, annual_days, annual_intensity


def z_pos(value, clim_mean, clim_std):
    std = np.where(
        clim_std <= 1e-6,
        np.nan,
        clim_std,
    )
    z = (value - clim_mean) / std
    z = np.clip(z, Z_CLIP_MIN, Z_CLIP_MAX)
    return np.where(
        z > 0,
        z,
        0.0,
    ).astype(np.float32)


def variable_row(ds, varname, iy):
    return (
        ds[varname]
        .isel(lat=iy)
        .transpose("time", "lon")
        .values
        .astype(np.float32, copy=False)
    )


def threshold_row(ds_thr, varname, ds_daily, iy):
    return (
        ds_thr[varname]
        .sel(doy_noleap=ds_daily["doy_noleap"])
        .isel(lat=iy)
        .transpose("time", "lon")
        .values
        .astype(np.float32, copy=False)
    )


def compute_doy_quantile(
    base,
    varname,
    percentile,
    brazil_mask,
    outname,
):
    print(f"[INFO] Computing {outname}: P{percentile}")

    base_var = base[varname].where(brazil_mask)
    half = ROLLING_WINDOW_DAYS // 2
    output = []

    for doy in range(1, 366):
        window = [
            (doy + offset - 1) % 365 + 1
            for offset in range(-half, half + 1)
        ]

        subset = base_var.where(
            base["doy_noleap"].isin(window),
            drop=True,
        )

        threshold = subset.quantile(
            percentile / 100.0,
            dim="time",
            skipna=True,
        )
        threshold = threshold.drop_vars(
            "quantile",
            errors="ignore",
        )
        output.append(threshold)

    da = xr.concat(
        output,
        dim="doy_noleap",
    )
    da = da.assign_coords(
        doy_noleap=np.arange(
            1,
            366,
            dtype=np.int16,
        )
    )
    da.name = outname
    return da


# ============================================================
# Daily data and sensitivity thresholds
# ============================================================

def open_daily_files(daily_dir):
    files = sorted(
        glob.glob(
            os.path.join(
                str(daily_dir),
                "ERA5_daily_Brazil_*.nc",
            )
        )
    )

    if not files:
        raise FileNotFoundError(
            f"No daily ERA5 files found in {daily_dir}"
        )

    keep_vars = {
        "Tmax",
        "Twbmax",
        "VPDmean",
    }

    datasets = []
    for path in files:
        ds = safe_open_dataset(
            path,
            decode_times=True,
            chunks=None,
        )
        drop = [
            var
            for var in ds.data_vars
            if var not in keep_vars
        ]
        if drop:
            ds = ds.drop_vars(drop)
        datasets.append(ds)

    ds = xr.concat(
        datasets,
        dim="time",
        data_vars="minimal",
        coords="minimal",
        compat="override",
    ).sortby("time")

    ds = ds.sel(
        time=slice(
            f"{START_YEAR}-01-01",
            f"{END_YEAR}-12-31",
        )
    )
    ds = ensure_complete_daily_calendar(ds)
    ds = remove_feb29(ds)
    ds = add_noleap_doy(ds)

    return ds


def ensure_sensitivity_thresholds(
    ds_daily,
    ds_thr,
    brazil_mask,
    output_dir,
):
    extra_file = (
        output_dir
        / "figure_01_sensitivity_thresholds_1991_2020.nc"
    )

    needed = {
        "DHW_VPDmean_P70": ("VPDmean", 70.0),
        "DHW_VPDmean_P80": ("VPDmean", 80.0),
        "HHW_Twbmax_P90": ("Twbmax", 90.0),
    }

    if extra_file.exists():
        try:
            with safe_open_dataset(extra_file) as old:
                for var in old.data_vars:
                    if var not in ds_thr:
                        ds_thr[var] = old[var].load()
        except Exception as exc:
            print(
                f"[WARN] Could not load sensitivity threshold cache: {exc}"
            )

    baseline = ds_daily.sel(
        time=slice(
            f"{BASE_START}-01-01",
            f"{BASE_END}-12-31",
        )
    )

    extra = xr.Dataset()
    changed = False

    for name, (varname, percentile) in needed.items():
        if name not in ds_thr:
            ds_thr[name] = compute_doy_quantile(
                baseline,
                varname,
                percentile,
                brazil_mask,
                name,
            )
            changed = True

        extra[name] = ds_thr[name]

    if changed or not extra_file.exists():
        safe_to_netcdf(
            extra,
            extra_file,
            encoding={
                var: {
                    "zlib": True,
                    "complevel": 4,
                    "dtype": "float32",
                }
                for var in extra.data_vars
            },
        )
        print(
            f"[OK] Saved sensitivity thresholds: {extra_file}"
        )

    return ds_thr


# ============================================================
# S1 — corrected Figure 01 summaries
# ============================================================

def unit_for_primary_metric(kind, metric):
    if metric == "frequency":
        return "events decade-1"
    if metric == "duration":
        return "days decade-1"
    if kind in {"HW", "HHW"}:
        return "degree_Celsius day decade-1"
    return "standardized severity decade-1"


def make_s1(trends, region_masks, weights, output_dir):
    rows = []

    for kind in KINDS:
        for metric in METRICS:
            var = f"{kind}_{metric}_trend_decade"
            pvar = f"{kind}_{metric}_pvalue"

            if var not in trends:
                raise KeyError(
                    f"Figure 01 field missing: {var}"
                )
            if pvar not in trends:
                raise KeyError(
                    f"Figure 01 p-value missing: {pvar}"
                )

            rows.extend(
                summarize_map(
                    trends[var],
                    trends[pvar],
                    region_masks,
                    weights,
                    scenario="primary_Figure01",
                    kind=kind,
                    metric=metric,
                    units=unit_for_primary_metric(
                        kind,
                        metric,
                    ),
                    significance_field=pvar,
                )
            )

    df = pd.DataFrame(rows)
    save_table(df, output_dir, 1)
    return df


# ============================================================
# S2 — unit-consistent primary DHW–HHW contrast
# ============================================================

def make_s2(trends, region_masks, weights, output_dir):
    contrast_var = (
        "DHW_minus_HHW_TmaxOnly_intensity_trend_decade"
    )
    dhw_pvar = "DHW_TmaxOnly_intensity_pvalue"

    if contrast_var not in trends:
        raise KeyError(
            f"Cross-regime field missing: {contrast_var}. "
            "Run the Figure 01 workflow first."
        )
    if dhw_pvar not in trends:
        raise KeyError(
            f"DHW common-scale p-value missing: {dhw_pvar}"
        )

    rows = summarize_map(
        trends[contrast_var],
        trends[dhw_pvar],
        region_masks,
        weights,
        scenario="corrected_primary_P75_P95_minlen3",
        kind="DHW_minus_HHW",
        metric="TmaxOnly_intensity",
        units="standardized severity decade-1",
        significance_field=dhw_pvar,
    )

    df = pd.DataFrame(rows)
    df["contrast_definition"] = (
        "DHW_TmaxOnly_intensity_trend_decade - "
        "HHW_TmaxOnly_intensity_trend_decade"
    )
    df["significance_note"] = (
        "Significance columns refer to the DHW Tmax-only intensity trend; "
        "no standalone p-value is assigned to the difference-of-slopes contrast."
    )

    save_table(df, output_dir, 2)
    return df


# ============================================================
# S3 — sensitivity with common Tmax-only intensity
# ============================================================

def sensitivity_file(output_dir, scenario):
    return (
        output_dir
        / f"figure_01_sensitivity_tmaxonly_{scenario}.nc"
    )


def cache_is_compatible(path, scenario):
    if not path.exists():
        return False

    try:
        with safe_open_dataset(
            path,
            decode_times=False,
            chunks=None,
        ) as ds:
            required = {
                "HHW_TmaxOnly_intensity_trend_decade",
                "HHW_TmaxOnly_intensity_pvalue",
                "DHW_TmaxOnly_intensity_trend_decade",
                "DHW_TmaxOnly_intensity_pvalue",
                "DHW_minus_HHW_TmaxOnly_intensity_trend_decade",
            }
            return (
                ds.attrs.get("scenario") == scenario
                and ds.attrs.get("comparison_intensity")
                == "common Tmax-only standardized severity"
                and ds.attrs.get("trend_significance_version")
                == TREND_SIGNIFICANCE_VERSION
                and required.issubset(set(ds.data_vars))
            )
    except Exception:
        return False


def compute_sensitivity_scenario(
    ds_daily,
    ds_thr,
    brazil_mask,
    cfg,
    output_dir,
):
    scenario = cfg["scenario"]
    min_len = int(cfg["min_len"])
    dhw_vpd_percentile = float(
        cfg["dhw_vpd_percentile"]
    )
    hhw_twb_percentile = float(
        cfg["hhw_twb_percentile"]
    )

    print(f"[INFO] Computing sensitivity: {scenario}")

    dhw_vpd_name = (
        "DHW_VPDmean_P75"
        if dhw_vpd_percentile == 75.0
        else f"DHW_VPDmean_P{int(dhw_vpd_percentile)}"
    )
    hhw_twb_name = (
        "HHW_Twbmax_P95"
        if hhw_twb_percentile == 95.0
        else f"HHW_Twbmax_P{int(hhw_twb_percentile)}"
    )

    time = pd.to_datetime(ds_daily.time.values)
    years = np.asarray(
        [timestamp.year for timestamp in time],
        dtype=np.int16,
    )
    year_axis = np.arange(
        START_YEAR,
        END_YEAR + 1,
        dtype=np.int16,
    )
    year_indices = {
        int(year): np.where(years == year)[0]
        for year in year_axis
    }

    lats = ds_daily.lat.values
    lons = ds_daily.lon.values
    ny = len(lats)
    nx = len(lons)
    mask_np = brazil_mask.values.astype(bool)

    output_arrays = {}
    for kind in ("HHW", "DHW"):
        for suffix in (
            "trend_decade",
            "pvalue",
            "lag1_autocorr_detrended",
            "lag1_critical",
            "MK_method_code",
            "original_MK_pvalue",
        ):
            output_arrays[
                f"{kind}_TmaxOnly_intensity_{suffix}"
            ] = np.full(
                (ny, nx),
                np.nan,
                dtype=np.float32,
            )

    for iy in range(ny):
        print(
            f"       {scenario}: latitude {iy + 1}/{ny}"
        )

        valid_lon_idx = np.where(
            mask_np[iy, :]
        )[0]
        if valid_lon_idx.size == 0:
            continue

        Tmax = variable_row(
            ds_daily,
            "Tmax",
            iy,
        )
        Twbmax = variable_row(
            ds_daily,
            "Twbmax",
            iy,
        )
        VPD = variable_row(
            ds_daily,
            "VPDmean",
            iy,
        )

        HHW_Twb_thr = threshold_row(
            ds_thr,
            hhw_twb_name,
            ds_daily,
            iy,
        )
        DHW_Tmax_thr = threshold_row(
            ds_thr,
            "DHW_Tmax_P95",
            ds_daily,
            iy,
        )
        DHW_VPD_thr = threshold_row(
            ds_thr,
            dhw_vpd_name,
            ds_daily,
            iy,
        )

        CLIM_Tmax_mean = threshold_row(
            ds_thr,
            "CLIM_Tmax_mean",
            ds_daily,
            iy,
        )
        CLIM_Tmax_std = threshold_row(
            ds_thr,
            "CLIM_Tmax_std",
            ds_daily,
            iy,
        )

        z_tmax = z_pos(
            Tmax,
            CLIM_Tmax_mean,
            CLIM_Tmax_std,
        )

        flags = {
            "HHW": Twbmax >= HHW_Twb_thr,
            "DHW": (
                (Tmax >= DHW_Tmax_thr)
                & (VPD >= DHW_VPD_thr)
            ),
        }

        validity = {
            "HHW": (
                np.isfinite(Twbmax)
                & np.isfinite(HHW_Twb_thr)
                & np.isfinite(Tmax)
                & np.isfinite(CLIM_Tmax_mean)
                & np.isfinite(CLIM_Tmax_std)
                & np.isfinite(z_tmax)
            ),
            "DHW": (
                np.isfinite(Tmax)
                & np.isfinite(VPD)
                & np.isfinite(DHW_Tmax_thr)
                & np.isfinite(DHW_VPD_thr)
                & np.isfinite(CLIM_Tmax_mean)
                & np.isfinite(CLIM_Tmax_std)
                & np.isfinite(z_tmax)
            ),
        }

        for ix in valid_lon_idx:
            for kind in ("HHW", "DHW"):
                valid_cell = validity[kind][:, ix]

                valid_by_year = {
                    int(year): int(
                        np.sum(
                            valid_cell[
                                year_indices[int(year)]
                            ]
                        )
                    )
                    for year in year_axis
                }

                if (
                    sum(
                        n >= MIN_VALID_DAYS_PER_YEAR
                        for n in valid_by_year.values()
                    )
                    < MIN_VALID_YEARS_FOR_TREND
                ):
                    continue

                event_mask = np.where(
                    valid_cell,
                    flags[kind][:, ix],
                    False,
                )

                _, _, annual_intensity = detect_runs_1d(
                    event_mask,
                    z_tmax[:, ix],
                    years,
                    min_len=min_len,
                )

                series = np.array(
                    [
                        annual_intensity[int(year)]
                        if valid_by_year[int(year)]
                        >= MIN_VALID_DAYS_PER_YEAR
                        else np.nan
                        for year in year_axis
                    ],
                    dtype=np.float32,
                )

                (
                    slope,
                    pvalue,
                    _,
                    _,
                    lag1,
                    lag1_critical,
                    method_code,
                    original_p,
                ) = robust_trend(
                    series,
                    year_axis,
                )

                base = (
                    f"{kind}_TmaxOnly_intensity"
                )
                output_arrays[
                    f"{base}_trend_decade"
                ][iy, ix] = slope
                output_arrays[
                    f"{base}_pvalue"
                ][iy, ix] = pvalue
                output_arrays[
                    f"{base}_lag1_autocorr_detrended"
                ][iy, ix] = lag1
                output_arrays[
                    f"{base}_lag1_critical"
                ][iy, ix] = lag1_critical
                output_arrays[
                    f"{base}_MK_method_code"
                ][iy, ix] = method_code
                output_arrays[
                    f"{base}_original_MK_pvalue"
                ][iy, ix] = original_p

    ds_out = xr.Dataset(
        {
            name: (("lat", "lon"), values)
            for name, values in output_arrays.items()
        },
        coords={
            "lat": lats,
            "lon": lons,
        },
        attrs={
            "scenario": scenario,
            "description": cfg["description"],
            "minimum_event_length_days": min_len,
            "DHW_VPD_percentile": dhw_vpd_percentile,
            "HHW_Twbmax_percentile": hhw_twb_percentile,
            "comparison_intensity": (
                "common Tmax-only standardized severity"
            ),
            "trend_method": "Theil-Sen median slope per decade",
            "significance_test": (
                "Original MK unless detrended lag-1 rank autocorrelation "
                "is significant; Hamed-Rao MK lag1 otherwise"
            ),
            "trend_significance_version": TREND_SIGNIFICANCE_VERSION,
            "baseline": f"{BASE_START}-{BASE_END}",
        },
    )

    ds_out[
        "DHW_minus_HHW_TmaxOnly_intensity_trend_decade"
    ] = (
        ds_out[
            "DHW_TmaxOnly_intensity_trend_decade"
        ]
        - ds_out[
            "HHW_TmaxOnly_intensity_trend_decade"
        ]
    ).astype("float32")

    ds_out[
        "DHW_minus_HHW_TmaxOnly_intensity_trend_decade"
    ].attrs.update({
        "units": "standardized severity decade-1",
        "definition": (
            "DHW_TmaxOnly_intensity_trend_decade - "
            "HHW_TmaxOnly_intensity_trend_decade"
        ),
    })

    out_file = sensitivity_file(
        output_dir,
        scenario,
    )

    safe_to_netcdf(
        ds_out,
        out_file,
        encoding={
            var: {
                "zlib": True,
                "complevel": 4,
                "dtype": "float32",
            }
            for var in ds_out.data_vars
        },
    )
    print(f"[OK] Saved sensitivity: {out_file}")
    return ds_out


def primary_sensitivity_dataset(main_trends):
    required = [
        "HHW_TmaxOnly_intensity_trend_decade",
        "HHW_TmaxOnly_intensity_pvalue",
        "DHW_TmaxOnly_intensity_trend_decade",
        "DHW_TmaxOnly_intensity_pvalue",
        "DHW_minus_HHW_TmaxOnly_intensity_trend_decade",
    ]
    missing = [
        var for var in required
        if var not in main_trends
    ]
    if missing:
        raise KeyError(
            "Main trend file is missing: "
            + ", ".join(missing)
        )

    return main_trends[required]


def make_s3(
    main_trends,
    scenario_datasets,
    region_masks,
    weights,
    output_dir,
):
    rows = []

    for cfg in SENSITIVITY_SCENARIOS:
        scenario = cfg["scenario"]

        if cfg["compute_from_main"]:
            ds = primary_sensitivity_dataset(
                main_trends
            )
        else:
            ds = scenario_datasets[scenario]

        contrast = ds[
            "DHW_minus_HHW_TmaxOnly_intensity_trend_decade"
        ]
        dhw_p = ds[
            "DHW_TmaxOnly_intensity_pvalue"
        ]

        rows.extend(
            summarize_map(
                contrast,
                dhw_p,
                region_masks,
                weights,
                scenario=scenario,
                kind="DHW_minus_HHW",
                metric="TmaxOnly_intensity",
                units="standardized severity decade-1",
                significance_field=(
                    "DHW_TmaxOnly_intensity_pvalue"
                ),
            )
        )

    df = pd.DataFrame(rows)
    df["contrast_definition"] = (
        "DHW_TmaxOnly_intensity_trend_decade - "
        "HHW_TmaxOnly_intensity_trend_decade"
    )
    df["significance_note"] = (
        "Significance columns refer to the DHW Tmax-only intensity trend; "
        "the contrast itself is a difference-of-slopes diagnostic."
    )

    save_table(
        df,
        output_dir,
        3,
    )
    return df


# ============================================================
# S4 — primary DHW temporal robustness
# ============================================================

def compute_trend_map_from_annual(
    annual_da,
    years_subset,
    min_valid_years,
):
    all_years = annual_da.year.values.astype(int)
    years_subset = np.asarray(
        years_subset,
        dtype=int,
    )
    selected = np.isin(
        all_years,
        years_subset,
    )

    years = all_years[selected]
    data = annual_da.sel(
        year=years
    ).values.astype(float)

    ny = data.shape[1]
    nx = data.shape[2]

    slope = np.full(
        (ny, nx),
        np.nan,
        dtype=np.float32,
    )
    pvalue = np.full_like(
        slope,
        np.nan,
    )
    lag1 = np.full_like(
        slope,
        np.nan,
    )
    method = np.full_like(
        slope,
        np.nan,
    )

    for iy in range(ny):
        print(
            f"       temporal trend: latitude {iy + 1}/{ny}"
        )
        for ix in range(nx):
            y = data[:, iy, ix]
            ok = np.isfinite(y)

            if ok.sum() < min_valid_years:
                continue

            (
                sen,
                p,
                _,
                _,
                r1,
                _,
                method_code,
                _,
            ) = robust_trend(
                y[ok],
                years[ok],
                min_valid_years=min_valid_years,
            )

            slope[iy, ix] = sen
            pvalue[iy, ix] = p
            lag1[iy, ix] = r1
            method[iy, ix] = method_code

    return slope, pvalue, lag1, method


def s4_cache_compatible(path):
    if not path.exists():
        return False
    try:
        with safe_open_dataset(
            path,
            decode_times=False,
            chunks=None,
        ) as ds:
            return (
                ds.attrs.get("trend_significance_version")
                == TREND_SIGNIFICANCE_VERSION
                and ds.attrs.get("metric")
                == "primary DHW intensity"
            )
    except Exception:
        return False


def compute_s4_dataset(
    annual,
    main_trends,
    output_dir,
    recompute,
):
    out_nc = (
        output_dir
        / "figure_01_dhw_intensity_extreme_year_robustness.nc"
    )

    if (
        not recompute
        and s4_cache_compatible(out_nc)
    ):
        print(f"[INFO] Loading compatible S4 cache: {out_nc}")
        return safe_open_dataset(out_nc)

    da = annual["DHW_intensity"]
    years_all = annual.year.values.astype(int)
    lats = annual.lat.values
    lons = annual.lon.values

    print("[INFO] S4: 1990–2022")
    (
        trend_2022,
        p_2022,
        lag1_2022,
        method_2022,
    ) = compute_trend_map_from_annual(
        da,
        np.arange(1990, 2023),
        min_valid_years=20,
    )

    print("[INFO] S4: 1990–2023")
    (
        trend_2023,
        p_2023,
        lag1_2023,
        method_2023,
    ) = compute_trend_map_from_annual(
        da,
        np.arange(1990, 2024),
        min_valid_years=20,
    )

    loyo_slopes = []

    for omitted in years_all:
        print(f"[INFO] S4 LOYO: omit {omitted}")
        years = [
            year
            for year in years_all
            if year != omitted
        ]

        slope, _, _, _ = compute_trend_map_from_annual(
            da,
            years,
            min_valid_years=20,
        )
        loyo_slopes.append(slope)

    loyo = np.stack(
        loyo_slopes,
        axis=0,
    )

    primary = main_trends[
        "DHW_intensity_trend_decade"
    ].values.astype(np.float32)

    ds = xr.Dataset(
        {
            "DHW_intensity_trend_primary_1990_2024": (
                ("lat", "lon"),
                primary,
            ),
            "DHW_intensity_trend_1990_2022": (
                ("lat", "lon"),
                trend_2022,
            ),
            "DHW_intensity_pvalue_1990_2022": (
                ("lat", "lon"),
                p_2022,
            ),
            "DHW_intensity_lag1_1990_2022": (
                ("lat", "lon"),
                lag1_2022,
            ),
            "DHW_intensity_MK_method_code_1990_2022": (
                ("lat", "lon"),
                method_2022,
            ),
            "DHW_intensity_trend_1990_2023": (
                ("lat", "lon"),
                trend_2023,
            ),
            "DHW_intensity_pvalue_1990_2023": (
                ("lat", "lon"),
                p_2023,
            ),
            "DHW_intensity_lag1_1990_2023": (
                ("lat", "lon"),
                lag1_2023,
            ),
            "DHW_intensity_MK_method_code_1990_2023": (
                ("lat", "lon"),
                method_2023,
            ),
            "DHW_intensity_LOYO_min": (
                ("lat", "lon"),
                np.nanmin(
                    loyo,
                    axis=0,
                ).astype(np.float32),
            ),
            "DHW_intensity_LOYO_q25": (
                ("lat", "lon"),
                np.nanpercentile(
                    loyo,
                    25,
                    axis=0,
                ).astype(np.float32),
            ),
            "DHW_intensity_LOYO_median": (
                ("lat", "lon"),
                np.nanmedian(
                    loyo,
                    axis=0,
                ).astype(np.float32),
            ),
            "DHW_intensity_LOYO_q75": (
                ("lat", "lon"),
                np.nanpercentile(
                    loyo,
                    75,
                    axis=0,
                ).astype(np.float32),
            ),
            "DHW_intensity_LOYO_max": (
                ("lat", "lon"),
                np.nanmax(
                    loyo,
                    axis=0,
                ).astype(np.float32),
            ),
            "DHW_intensity_LOYO_range": (
                ("lat", "lon"),
                (
                    np.nanmax(loyo, axis=0)
                    - np.nanmin(loyo, axis=0)
                ).astype(np.float32),
            ),
        },
        coords={
            "lat": lats,
            "lon": lons,
        },
        attrs={
            "metric": "primary DHW intensity",
            "DHW_intensity_definition": (
                "0.5*z+(Tmax) + 0.5*z+(VPD)"
            ),
            "purpose": (
                "Test whether primary DHW intensity trend is dominated "
                "by 2023/2024 or a single year."
            ),
            "trend_significance_version": TREND_SIGNIFICANCE_VERSION,
            "primary_period": "1990-2024",
            "truncated_periods": "1990-2022; 1990-2023",
            "LOYO": (
                "Leave-one-year-out Theil-Sen trend for every omitted "
                "year from 1990 through 2024."
            ),
        },
    )

    safe_to_netcdf(
        ds,
        out_nc,
        encoding={
            var: {
                "zlib": True,
                "complevel": 4,
                "dtype": "float32",
            }
            for var in ds.data_vars
        },
    )

    print(f"[OK] Saved S4 NetCDF: {out_nc}")
    return ds


def make_s4(
    annual,
    main_trends,
    region_masks,
    weights,
    output_dir,
    recompute,
):
    ds = compute_s4_dataset(
        annual,
        main_trends,
        output_dir,
        recompute,
    )

    specs = [
        (
            "primary_1990_2024",
            ds[
                "DHW_intensity_trend_primary_1990_2024"
            ],
            main_trends[
                "DHW_intensity_pvalue"
            ],
            "DHW_intensity_pvalue",
        ),
        (
            "truncated_1990_2022",
            ds[
                "DHW_intensity_trend_1990_2022"
            ],
            ds[
                "DHW_intensity_pvalue_1990_2022"
            ],
            "DHW_intensity_pvalue_1990_2022",
        ),
        (
            "truncated_1990_2023",
            ds[
                "DHW_intensity_trend_1990_2023"
            ],
            ds[
                "DHW_intensity_pvalue_1990_2023"
            ],
            "DHW_intensity_pvalue_1990_2023",
        ),
        (
            "LOYO_median",
            ds["DHW_intensity_LOYO_median"],
            None,
            "",
        ),
        (
            "LOYO_min",
            ds["DHW_intensity_LOYO_min"],
            None,
            "",
        ),
        (
            "LOYO_max",
            ds["DHW_intensity_LOYO_max"],
            None,
            "",
        ),
        (
            "LOYO_range",
            ds["DHW_intensity_LOYO_range"],
            None,
            "",
        ),
    ]

    rows = []

    for scenario, values, pvalues, pfield in specs:
        rows.extend(
            summarize_map(
                values,
                pvalues,
                region_masks,
                weights,
                scenario=scenario,
                kind="DHW",
                metric="primary_intensity",
                units="standardized severity decade-1",
                significance_field=pfield,
            )
        )

    df = pd.DataFrame(rows)
    df["DHW_intensity_definition"] = (
        "0.5*z+(Tmax) + 0.5*z+(VPD)"
    )

    save_table(
        df,
        output_dir,
        4,
    )

    return ds, df


# ============================================================
# Diagnostic table for sensitivity component maps
# ============================================================

def make_sensitivity_detail_table(
    main_trends,
    scenario_datasets,
    region_masks,
    weights,
    output_dir,
):
    rows = []

    for cfg in SENSITIVITY_SCENARIOS:
        scenario = cfg["scenario"]

        if cfg["compute_from_main"]:
            ds = primary_sensitivity_dataset(
                main_trends
            )
        else:
            ds = scenario_datasets[scenario]

        for kind in ("HHW", "DHW"):
            var = (
                f"{kind}_TmaxOnly_intensity_trend_decade"
            )
            pvar = (
                f"{kind}_TmaxOnly_intensity_pvalue"
            )

            rows.extend(
                summarize_map(
                    ds[var],
                    ds[pvar],
                    region_masks,
                    weights,
                    scenario=scenario,
                    kind=kind,
                    metric="TmaxOnly_intensity",
                    units="standardized severity decade-1",
                    significance_field=pvar,
                )
            )

    df = pd.DataFrame(rows)

    path = (
        output_dir
        / "Diagnostic_Table_threshold_duration_sensitivity_all_metrics.csv"
    )
    df.to_csv(path, index=False)
    print(f"[OK] Saved diagnostic table: {path}")


# ============================================================
# Main
# ============================================================

def main():
    warnings.filterwarnings("ignore")

    args = parse_args()
    paths = configure_paths(args)

    print("=" * 82)
    print("FIGURE 01 — SUPPLEMENTARY ROBUSTNESS S1–S4")
    print("=" * 82)
    print(f"Figure 01 root : {paths['root']}")
    print(f"Output          : {paths['output']}")
    print("S2/S3 contrast : common Tmax-only standardized severity")
    print(
        "Significance   : original MK unless significant detrended lag-1; "
        "Hamed-Rao lag1 otherwise"
    )
    print("=" * 82)

    trends = safe_open_dataset(
        paths["trends"],
        decode_times=False,
        chunks=None,
    )
    annual = safe_open_dataset(
        paths["annual"],
        decode_times=False,
        chunks=None,
    )
    ds_thr = safe_open_dataset(
        paths["thresholds"],
        decode_times=False,
        chunks=None,
    )

    # Fail early when the Figure 01 trend file lacks required common-scale fields.
    required_corrected = {
        "HHW_TmaxOnly_intensity_trend_decade",
        "DHW_TmaxOnly_intensity_trend_decade",
        "DHW_minus_HHW_TmaxOnly_intensity_trend_decade",
    }

    if not required_corrected.issubset(
        set(trends.data_vars)
    ):
        raise RuntimeError(
            "The supplied Figure 01 trend file is not the corrected version. "
            "Missing common Tmax-only HHW/DHW fields."
        )

    lats = trends.lat.values
    lons = trends.lon.values

    brazil_mask = make_brazil_mask(
        lats,
        lons,
        paths["brazil_shp"],
    )
    region_masks = build_region_masks(
        lats,
        lons,
        brazil_mask,
        paths["biomes_shp"],
    )
    weights = area_weights_for_grid(
        lats,
        lons,
    )

    # S1 is generated from the main Figure 01 trends.
    make_s1(
        trends,
        region_masks,
        weights,
        paths["output"],
    )

    # S2 always regenerated from common-scale contrast.
    make_s2(
        trends,
        region_masks,
        weights,
        paths["output"],
    )

    # S4 uses primary DHW intensity and the Figure 01 significance framework.
    s4_ds, _ = make_s4(
        annual,
        trends,
        region_masks,
        weights,
        paths["output"],
        args.recompute_s4,
    )

    # S3 sensitivity.
    nonprimary = [
        cfg
        for cfg in SENSITIVITY_SCENARIOS
        if not cfg["compute_from_main"]
    ]

    scenario_datasets = {}

    need_daily = any(
        args.recompute_sensitivities
        or not cache_is_compatible(
            sensitivity_file(
                paths["output"],
                cfg["scenario"],
            ),
            cfg["scenario"],
        )
        for cfg in nonprimary
    )

    ds_daily = None

    if need_daily:
        ds_daily = open_daily_files(
            paths["daily_dir"]
        )

        # Align the daily fields with the Figure 01 grid.
        ds_daily = ds_daily.sel(
            lat=trends.lat,
            lon=trends.lon,
        )

        ds_thr = ensure_sensitivity_thresholds(
            ds_daily,
            ds_thr,
            brazil_mask,
            paths["output"],
        )

    for cfg in nonprimary:
        cache = sensitivity_file(
            paths["output"],
            cfg["scenario"],
        )

        if (
            not args.recompute_sensitivities
            and cache_is_compatible(
                cache,
                cfg["scenario"],
            )
        ):
            print(
                f"[INFO] Loading compatible sensitivity cache: {cache.name}"
            )
            scenario_datasets[
                cfg["scenario"]
            ] = safe_open_dataset(
                cache,
                decode_times=False,
                chunks=None,
            )
        else:
            scenario_datasets[
                cfg["scenario"]
            ] = compute_sensitivity_scenario(
                ds_daily,
                ds_thr,
                brazil_mask,
                cfg,
                paths["output"],
            )

    make_s3(
        trends,
        scenario_datasets,
        region_masks,
        weights,
        paths["output"],
    )

    make_sensitivity_detail_table(
        trends,
        scenario_datasets,
        region_masks,
        weights,
        paths["output"],
    )

    readme = (
        paths["output"]
        / "README_figure_01_supplementary_robustness.txt"
    )

    readme.write_text(
        "\n".join([
            "Figure 01 supplementary robustness outputs",
            "==========================================",
            "",
            "S1 — Figure 01 primary regime summaries.",
            "     Primary regime-specific intensity units are retained.",
            "",
            "S2 — Primary HHW-DHW contrast.",
            "     Uses DHW_minus_HHW_TmaxOnly_intensity_trend_decade.",
            "",
            "S3 — Sensitivity of the HHW-DHW contrast.",
            "     Every scenario compares HHW and DHW using common Tmax-only",
            "     standardized severity.",
            "",
            "S4 — Temporal robustness of PRIMARY DHW intensity.",
            "     DHW primary intensity remains 0.5*z+(Tmax)+0.5*z+(VPD).",
            "",
            "Significance methodology:",
            TREND_SIGNIFICANCE_VERSION,
            "",
            "Important: direct subtraction of primary DHW and HHW intensity",
            "fields is not used anywhere in S2 or S3.",
        ]),
        encoding="utf-8",
    )

    trends.close()
    annual.close()
    ds_thr.close()

    if ds_daily is not None:
        ds_daily.close()

    try:
        s4_ds.close()
    except Exception:
        pass

    for ds in scenario_datasets.values():
        try:
            ds.close()
        except Exception:
            pass

    print("[DONE] Supplementary Tables S1–S4 generated.")


if __name__ == "__main__":
    main()
